### ISSUE TITLE
Petit bug notifications - choix d'une image / icones

### ISSUE THREAD

**Issue by rhcpdu13** [jared-94/JeedomConnect#103]
Bonjour,
J'ai un petit bug à vous faire remonter, qui concerne les options des notifications. Si je souhaite ajouter une image ou icône dans la liste, le bouton valider ne fonctionne pas et j'ai une alerte dans les notifs de jeedom : 

/index.php?v=d&amp;p=JeedomConnect&amp;m=JeedomConnect&amp;id=254 line 2 &gt; injectedScript | 1014 | TypeError: _params is undefined

Merci !

**Comment by tomitomas** [comment]
salut 

il faudrait nous préciser quelle version tu utilises & si tu es en stable ou un beta...!?

tu utilises quoi comme browser ? il est à jour ?

**Comment by rhcpdu13** [comment]
Oups désolé !! 
Alors tout est à jour, en béta, à savoir :
2021-06-03 16:34:20 pour le plugin et 0.21.1 pour lapk
Si vous avez besoin de logs dites le moi :)

**Comment by jared-94** [comment]
Désolé j'ai zappé ton message.
As tu toujours ce problème avec les dernières versions ?

Si oui ça serait bien oui d'avoir des log en debug, et sur la console de chrome

**Comment by jared-94** [comment]
Je ferme le sujet.
Ouvre le de nouveau si le problème persiste
