### ISSUE TITLE
Activation geofencing

### ISSUE THREAD

**Issue by davidk76** [jared-94/JeedomConnect#105]
Bonjour.
J'aimerais profiter de cette application mais je ne peux pas activer le geofencing.
Quand je l'active j'ai une fenêtre qui s'ouvre ( politique de confidentialité) mais je n'ai aucune commande possible !
Du coup quand je referme cette fenêtre je reviens au point de départ mais sans l'option geofencing active.
Je dois passer à côté de quelque chose mais je ne vois pas.
C'est pourquoi je post ce message 😀.

**Comment by jared-94** [comment]
Tu as normalement un bouton ok dans cette fenêtre

**Comment by davidk76** [comment]
Je ne le vois pas !
Il est en bas j'imagine à droite ?

**Comment by davidk76** [comment]
![Screenshot_20210701-102809](https://user-images.githubusercontent.com/86768832/124093785-73d13600-da58-11eb-9a87-fbc0a621b8c5.png)

**Comment by davidk76** [comment]
Je ne sais pas pourquoi je n'ai pas accès à la commande "ok"

**Comment by tomitomas** [comment]
impossible de scroller vers le bas ? 

autre solution (temporaire) dans les param du telephone, réduite la taille de police par défaut, relance JC pour valider ces conditions, remets la taille de police dont tu as besoin

**Comment by jared-94** [comment]
Oui soit tu as une très petite résolution sur ton écran soit des textes trop gros !

**Comment by davidk76** [comment]
![Screenshot_20210701-120337](https://user-images.githubusercontent.com/86768832/124106537-95d0b580-da64-11eb-8371-1bcfaef694e7.png)
La taille de la police était au maximum.
Merci beaucoup pour votre aide !
