### ISSUE TITLE
Suggestion : slider vertical & image 

### ISSUE THREAD

**Issue by Web-svg** [jared-94/JeedomConnect#117]
Bonjour,

Est-il possible de pouvoir disposer d'un slider que l'on positionnerait à la verticale ? (Un widget tiers de @nodoom côté dashboard) ?
~ un peu comme sur une table de mixage et de pouvoir lui associer une image 'pickée' ?
Cordialement
++

**Comment by jared-94** [comment]
Qu'entends tu par associer une image pickee ?

**Comment by jared-94** [comment]
Salut,
J'ai pas la pj !
Je veux bien faire des trucs, mais faudrait être un peu précis...

**Comment by Web-svg** [comment]
Hello,
Et bien les PJ y étaient pourtant ... mais bon, comme c'était juste pour 
illustrer l'idée et que je dois reconnaître que ce n'est pas forcément 
top, voici l'idée de rendus tels que crées par des dev d'apps sur le NET 
(exemple avec theia et eurolite)

Si cela ne fonctionne pas, on peut voir en mp...
++

------ Message d'origine ------
De: "jared-94" ***@***.***>
À: "jared-94/JeedomConnect" ***@***.***>
Cc : "Web-svg" ***@***.***>; "Author" ***@***.***>
Envoyé : 10/11/2021 23:09:22
Objet : Re: [jared-94/JeedomConnect] Suggestion : slider vertical & 
image (#117)

**Comment by tomitomas** [comment]
@Web-svg les PJ par mail ne semblent pas etre integrées a l'issue 
Il faudrait mieux que tu upload l img directement sur github

**Comment by Web-svg** [comment]
Hello,
Désolé pour le retard ...
voici les images en question
![eurolite1](https://user-images.githubusercontent.com/63095113/143611531-37b8638e-d4eb-4d3a-9872-2f02b7bbdaf4.png)
![eurolite2](https://user-images.githubusercontent.com/63095113/143611539-a9cbbf23-b266-48e9-90a5-7399a11130b2.png)
![theia](https://user-images.githubusercontent.com/63095113/143611546-e0c45ff4-001b-47b1-917c-35498bc6f1ef.png)

![bargraph_base_green](https://user-images.githubusercontent.com/63095113/143611627-3e28296e-a3da-4ffa-92cf-8735351b3731.png)
![bargraph_base_white](https://user-images.githubusercontent.com/63095113/143611631-e56b7a72-f75f-4db5-ba9c-b3c3f4c0e28f.png)
![bargraph_base_amber](https://user-images.githubusercontent.com/63095113/143611632-ce504d7f-5b36-421e-9dd4-bfa54bd241df.png)
![bargraph_base_blue](https://user-images.githubusercontent.com/63095113/143611633-be95d394-1f51-4f0b-a6b9-fa1660fceb93.png)

**Comment by tomitomas** [comment]
slider vertical dispo en beta 1.1.1

(ajout d'image non prévu pour le moment)

**Comment by jared-94** [comment]
Si on peut choisir une image de fond pour le slider et le curseur ;-)

**Comment by tomitomas** [comment]
Autant pour moi ! :)
