### ISSUE TITLE
Labels multiples dans les sous titres

### ISSUE THREAD

**Issue by GuiPoM** [jared-94/JeedomConnect#139]
Salut ! 

J'ai vu dans la documentation qu'on peut mettre des informations multiples dans les labels. Du coup j'ai fait un label de ce genre: 
`#[Garage][Etat porte][Fermée]# ==1 ? (#[Garage][Etat porte][Portillon]# == 1 ? "Portillon" : "Fermée") : "Ouverte"`
Et ça marche très bien !

Et puis j'ai essayé autre chose pour ma porte d'entrée, afficher deux labels, à savoir verrouillé/pas et ouvert/fermé, et là ça ne marche pas:
`#[Entrée][Porte][Etat]# === 1 ? "Ouverte" : "Fermée"` => ok
`(#[Entrée][Porte][Etat]# === 1 ? "Ouverte" : "Fermée")` => ok
`blabla (#[Entrée][Porte][Etat]# === 1 ? "Ouverte" : "Fermée")` => ne marche pas

et donc évidemment:
`(#[Entrée][Porte][Etat]# === 1 ? "Ouverte" : "Fermée")  #[Entrée][Nuki][Nom etat]#` => ne marche pas non plus.

Je ne sais pas quelles sont les limites des sous-titres, mais ça me serait pratique de combiner cette info à ce niveau là et de ne pas bidouiller des virtuels et autres, donc si ça aurait du marcher et que ce n'est pas le cas, ça me rassurerait ! 😀

**Comment by tomitomas** [comment]
teste 
`(#[Entrée][Porte][Etat]# === 1 ? "Ouverte" : "Fermée") + " " + #[Entrée][Nuki][Nom etat]#`

**Comment by GuiPoM** [comment]
Non, malheureusement c'est pareil, seule la dernière variable est remplacée, le reste est affiché sous forme brute.
Sachant que `#[Entrée][Porte][Etat]#` est bien dans les infos, et que ça fonctionne tout seul, comme je l'ai dit.

**Comment by tomitomas** [comment]
`#[Entrée][Nuki][Nom etat]#` est ajouté en info supplémentaire ? 

ya pas de raison que ca ne fonctionne pas. 
je viens de tester et je te confirme que c'est OK.

**Comment by GuiPoM** [comment]
C'est étrange, mais oui je confirme que j'ai du faire ce qu'il faut: 
![image](https://user-images.githubusercontent.com/11942518/140815961-dad37097-7e87-4421-be19-75e02fceee89.png)

**Comment by tomitomas** [comment]
sur un widget `générique action` je reproduis en effet ... 
@jared-94 code différent en fonction du type de widget sélectionné !?

**Comment by GuiPoM** [comment]
Aucune idée, je suis tout nouveau sur l'app et je préparais une petite vidéo pour présenter l'app, et je suis tombé par hasard sur ce petit soucis ^^

**Comment by jared-94** [comment]
Le sous titre (ou le titre) doit être soit une chaîne, soit une expression JS qui renvoie une chaîne.
Pour ce que tu veux faire tu es obligé de dupliquer du code :
`#[Entrée][Porte][Etat]# === 1 ? "Ouverte" + #[Entrée][Nuki][Nom etat]#  : "Fermée" + #[Entrée][Nuki][Nom etat]#`

**Comment by GuiPoM** [comment]
Désolé de vous faire perdre du temps sur un point de détail.
Je n'avais pas compris sur le coup que la chaine était injectée dans l'interface, maintenant que je le lis, oui forcément, ça a du sens.
Par contre seules les sections `#[Entrée][Nuki][Nom etat]#` sont remplacées avec ce que tu proposes, le reste est affiché sous forme brute.
Comme si le code transformait les variables, mais travaillait sur une chaine brute dans mon cas, a ce niveau.

**Comment by tomitomas** [comment]
@GuiPoM 
Ce que je t ai proposé plus haut fonctionne aussi en fait. Le probleme vient de ton equipement pas de la formule. 
Depuis ton tel, clic sur ce widget pour avoir la plus detail et partages un screenshot de cette vue stp

**Comment by GuiPoM** [comment]
> @GuiPoM Depuis ton tel, clic sur ce widget pour avoir la vue detail et partages un screenshot de cette vue stp

Voilà, j'espère que c'est ce dont tu as besoin:
![image](https://user-images.githubusercontent.com/11942518/140895453-be37637c-437f-410d-a4a7-99544077a2c0.png)

![image](https://user-images.githubusercontent.com/11942518/140895486-e26d9efa-c7a6-4147-87d4-4933d128cfd0.png)
![image](https://user-images.githubusercontent.com/11942518/140895563-7b60c15d-73cd-4276-8205-3d0ea844672e.png)

**Comment by tomitomas** [comment]
ajoute des parentheses autour de ton test
`( etat === 1 ) ? .... `

**Comment by GuiPoM** [comment]
Oh ça j'ai déjà tenté il y a un moment
`(#[Entrée][Porte][Etat]# === 1) ? ("Ouverte" + #[Entrée][Nuki][Nom etat]#) : ("Fermée" + #[Entrée][Nuki][Nom etat]#)`

**Comment by tomitomas** [comment]
je viens de faire le test avec une config similaire sur un générique action, en ajoutant les info supplémentaire également : 
copie/colle ca
`((#[Entrée][Porte][Etat]# == 1) ? 'Ouvert' : 'Fermé') + " " + #[Entrée][Nuki][Nom etat]#`

et montre le résultat que ca te fait stp

**Comment by GuiPoM** [comment]
Je suis désolé si ça parait surprenant que ça ne marche pas, j'y mets du mien pourtant ^^

Voilà ce que ça donne:
![image](https://user-images.githubusercontent.com/11942518/140921855-fb45d2b0-29fd-4c31-9135-dfa175edb574.png)
![image](https://user-images.githubusercontent.com/11942518/140921952-a72ad301-f16e-47c4-9355-388610422a52.png)
![image](https://user-images.githubusercontent.com/11942518/140921977-05a84f2c-08e2-4767-bf82-c9cbea7a508e.png)

**Comment by tomitomas** [comment]
t'es sur quelle version de l'application ?
(menu / a propos)

**Comment by GuiPoM** [comment]
J'aurais pu commencer par ça: 
Android, v0.23.0
Plugin 2021-10-07 16:16:42

**Comment by tomitomas** [comment]
pcq chez moi

![image](https://user-images.githubusercontent.com/12429858/140922736-50069695-0f34-4327-8057-5e661eb5184d.png)

**Comment by jared-94** [comment]
Essaie en ajoutant des double quote 

`#[Entrée][Porte][Etat]# === 1 ? "Ouverte " + "#[Entrée][Nuki][Nom etat]#" : "Fermée " + "#[Entrée][Nuki][Nom etat]#"`

**Comment by GuiPoM** [comment]
Super, ça marche ! C'est pas trivial mais je commencer à comprendre pourquoi il n'interprétait pas la chaine à générer.

**Comment by tomitomas** [comment]
ce n'est pas si évident que ca, car mon exemple fonctionne avec les simple quotes ... 

l'essentiel c'est que tu aies le résultat que tu souhaites !
