### ISSUE TITLE
Publication dans le PlayStore

### ISSUE THREAD

**Issue by aztazt** [jared-94/JeedomConnect#14]
Bonjour,
Merci pour cet excellent travail, et donné gratuitement à la communauté en plus !
Serait-il envisageable d'en faire (en parallèle) une application payante, publiée sur le PlayStore, afin de rendre l'utilisation de l'application possible pour les utilisateurs Google qui bénéficient du "Advanced Protection Program" et pour qui l'installation d'APK n'est pas possible ?
Ca me permettrait en plus de rétribuer l'auteur par ce biais :)

**Comment by jared-94** [comment]
Bonjour,
oui j'envisage de mettre l'app sur le Play store !

Par contre le côté payant je ne pense pas non...

**Comment by tomitomas** [comment]
dispo pour les versions stable
https://play.google.com/store/apps/details?id=com.jeedomconnect.app
