### ISSUE TITLE
Bug widget vignette dans groupe 

### ISSUE THREAD

**Issue by zeldhaking** [jared-94/JeedomConnect#143]
Hello, depuis la dernière version mes widgets forcés en affichage vignette dans un groupe apparaissent en affichage carte.

**Comment by tomitomas** [comment]
Salut, 

la suite de la discussion sera ici : 
https://community.jeedom.com/t/widget-force-en-mode-carte-dans-un-groupe-passe-en-mode-vignette/71822

merci :)

**Comment by zeldhaking** [comment]
Top, merci 😉
