### ISSUE TITLE
Bugs Lumière à variation

### ISSUE THREAD

**Issue by loicdelecroix** [jared-94/JeedomConnect#16]
Bonjour,

Merci pour cet excellent travail! Jeedom manquait cruellement d'une belle interface graphique, et ton combo plugin/appli est vraiment très bien pensé et fonctionnel, bravo !

2 petits bugs rencontré pour ma part sur un widget "Lumière à variation" au niveau de l'application (version 0.13.3)

Tout d'abord, celle-ci est toujours montré en "On" sur l'application au démarrage, malgré le fait qu'elle soit éteinte. La config est pourtant bonne coté plugin Jeedom : 
![Capture](https://user-images.githubusercontent.com/45817385/105095526-0f23af80-5aa6-11eb-9488-d27e5b067816.PNG)
 
C'est la seule lumière qui me cause ce soucis, toutes les autres (qui sont à variation de couleur) sont OK.

Enfin, comme tu peux le voir sous la vidéo ci-dessous, dès que j'essaye de l'ouvrir, l'application passe en page blanche : 
https://user-images.githubusercontent.com/45817385/105095844-835e5300-5aa6-11eb-8267-917cb61fff0c.mp4

J'ai essayé de la supprimer et de la re créer, mais rien n'y fait, le problème persiste ...
Si besoin de log ou autre, n'hésite pas à demander !

**Comment by jared-94** [comment]
Bonjour
Ta commande État est bien une info de type binaire ?

**Comment by loicdelecroix** [comment]
Yes
![Selection_010](https://user-images.githubusercontent.com/45817385/105165239-56498900-5b16-11eb-8bd3-1b31c134c7fd.png)

**Comment by jared-94** [comment]
Je viens de regardé mon code pour le status, j'utilise la condition 'intensité > 0'
Ta commande d'intensité est-elle correcte ?

**Comment by loicdelecroix** [comment]
Normalement oui : 
![Selection_011](https://user-images.githubusercontent.com/45817385/105184951-40e15880-5b30-11eb-849e-fb7a5fa105b0.png)
![Selection_012](https://user-images.githubusercontent.com/45817385/105184955-40e15880-5b30-11eb-9fb6-3f7436268805.png)
![Selection_013](https://user-images.githubusercontent.com/45817385/105184957-4179ef00-5b30-11eb-8a1a-c6783b247830.png)

**Comment by jared-94** [comment]
OK ça vient de là alors !
Pour mes modules Fibaro, la luminosité se met à 0 quand on éteint, du coup je pensait que c'était le comportement 'normal'
Je vais modifier pour régler ça !

**Comment by loicdelecroix** [comment]
Oh d'accord !
Pour info, c'est une ampoule Philips HUE récupéré via le plugin Deconz :)
Même comportement avec un bandeau de LED OSRAM qui garde la dernière valeur (idem, via le plugin Deconz)

Merci pour les infos et l'investigation !

**Comment by jared-94** [comment]
Normalement corrigé dans la 0.14.3. Tu confirmes ?

**Comment by loicdelecroix** [comment]
Je confirme, le bouton est bien sur OFF en ouvrant l'appli ! Merci :)
