### ISSUE TITLE
Bug historique température

### ISSUE THREAD

**Issue by loicdelecroix** [jared-94/JeedomConnect#17]
Bonsoir, 2e petit bug que je me permets de remonter.

Sur un de mes capteurs de température, l'échelle ne se met pas à jour sur l'historique (tous les autres sont OK) : 
![Screenshot_20210119_223710_com android jeedomconnect](https://user-images.githubusercontent.com/45817385/105096389-447ccd00-5aa7-11eb-9148-437e83e38151.jpg)

L'historique vu sur Jeedom : 
![Capture](https://user-images.githubusercontent.com/45817385/105096345-36c74780-5aa7-11eb-898b-7928e7f909f4.PNG)

Y'a-t-il moyen d'ajuster l'échelle pour ce capteur ? Je précise que le zoom avec les doigts ne fonctionne pas, seul l'échelle de temps change, mais pas l'échelle des températures.

**Comment by jared-94** [comment]
Oui j'ai encore quelques petites choses à voir avec l'historique !

**Comment by loicdelecroix** [comment]
Ca marche, j'attendrais les mises à jour alors :) merci !

**Comment by jared-94** [comment]
Salut,

est-ce que le soucis est réglé dans la 0.14.3 ?

**Comment by loicdelecroix** [comment]
Hello Jared,

Pas encore eu le temps d'installer, je test ça ce soir en rentrant !

**Comment by loicdelecroix** [comment]
Hello,

Je viens d'installer, c'est tout bon, l'affichage de l'historique est niquel :)

Merci !
