### ISSUE TITLE
Erreur HTTP 401 

### ISSUE THREAD

**Issue by Khomotica** [jared-94/JeedomConnect#172]
Bonjour,
Depuis que je suis passé en connexion SSO sur Jeedom (via REMOTE_USER + kerberos), je n'arrive plus à me connecter depuis mon tél sur JeedomConnect et j'ai le code retour 401 :

![image](https://user-images.githubusercontent.com/59171393/148131956-33afa15f-51e2-4d90-ae0c-4005f2a5604a.png)

Y'a-t-il un moyen de faire de l'authent basic dans l'application ? (possibilité de saisir un login/mot de passe).

**Comment by tomitomas** [comment]
Bonjour

Le login/mdp sont saisie une fois que la connexion au jeedom est réalisée et est en succes.

Est ce que tu as essayé via le qr code (apres l avoir régénéré) ?

**Comment by Khomotica** [comment]
Merci pour ton retour rapide.
Oui j'ai relancé le QR code et idem ça me fait un code 401.

Je viens d'autoriser sur la conf Apache l'adresse IP de mon tél et effectivement après avoir saisi mes identifiants LDAP dans l'appli, ces nouveaux "credentials" sont stockés dans l'application
En remettant la conf apache d'origine, j'arrive à me connecter sans problème maintenant.

Donc pas d'anomalie et merci encore.

**Comment by tomitomas** [comment]
je serai toi, je tenterai quand meme une déconnexion (menu / pref / se déconnecter) 
puis une reconnexion

ca serait quand meme un peu con que tu sois obligé de changer ta conf Apache à chaque fois que tu as besoin de te reconnecter ... 
(et les demandes de connexion peuvent être "fréquente" (et automatique) lorsque l'app est killée un certain temps! )

**Comment by Khomotica** [comment]
La je viens de killer et/ou arrêter de force l'appli et la reconnexion se fait toute seule.
Le problème est uniquement lié à la 1ère connexion ou le serveur renvoi 401 si la méthode negotiate (SSO dans mon cas) puis le basic authent ne sont pas accomplies.
Il faudra peut-être proposer dans la même page l'URL, le login et le password pour tenter une connexion en basic authent et ne pas tomber sur l'erreur dans mon cas.

**Comment by tomitomas** [comment]
A suivre ... 
Mais 1er cas en 1 an, faudra analyser le ROI de modifier le type de connexion avant de faire quoique ce soit :D

**Comment by Khomotica** [comment]
je suis d'accord.
Après effectivement je ne sais pas combien dans la communauté Jeedom font du SSO
