### ISSUE TITLE
Impossible de supprimer des groupes "fantôme"

### ISSUE THREAD

**Issue by tibidi** [jared-94/JeedomConnect#174]
Dans l'application web j'ai des groupes "fantôme". Je ne sais pas d'où ils viennent. Quand j'essaie de les supprimer je vois ceci:

![image](https://user-images.githubusercontent.com/27189952/148256202-d879be8f-ed63-489a-afab-42454e2d3cf9.png)

Je suis en version 1.1.0 (Android/Plugin JeeDom)

**Comment by tomitomas** [comment]
et depuis l'application ? ca donne quoi ?

**Comment by tomitomas** [comment]
c'est quand même pas normal , ils ne sont pas apparus tout seuls :)

si tu le souhaites tu peux partager ton fichier présent dans `plugins\JeedomConnect\data\configs\`
qui se nomme `<apiKey de ton équipement>.json` => tu retrouves l'info 'apiKey' sur la page de configuration de ton équipement JC

**Comment by tibidi** [comment]
Voici le fichier. En réalité, ce sont les 2 widgets suivants les fautifs. Ils ne correspondent à rien dans la vue de la configuration sur l'interface web. Après suppression dans le 2 fichiers de config je n'ai plus les deux lignes comme avant.  Pour info j'avais essayé la version beta de jeedom connect il y a qq temps. Cela pourrait expliquer...

```
            {
                "index": 11,
                "widgetId": 10,
                "id": 9
            },
            {
                "index": 10,
                "widgetId": 11,
                "id": 9
            },
```


[config.zip](https://github.com/jared-94/JeedomConnect/files/7820574/config.zip)

**Comment by tomitomas** [comment]
si tout est rentrée dans l'ordre, alors pas de soucis :)
