### ISSUE TITLE
L application iPhone  plante au démarrage

### ISSUE THREAD

**Issue by tibidi** [jared-94/JeedomConnect#175]
Tout est dans le titre. Depuis la dernière version l application plante au démarrage sur un iPhone 6.

**Comment by tomitomas** [comment]
"Bonsoir" ...

... et sinon malheureusement le titre ne fait pas tout ! 
Il faut qlq infos en plus pour aider. Version ios  ? Version JC ?

**Comment by tibidi** [comment]
Version jc 1.1.0
ios Version 12.5.5

**Comment by tomitomas** [comment]
Peut etre une petite recherche sur le forum : 
https://community.jeedom.com/t/maj-jeeconnect/75679/15?u=tomitomas
