### ISSUE TITLE
Seul 1 widget d'un groupe s'affiche

### ISSUE THREAD

**Issue by loicdelecroix** [jared-94/JeedomConnect#196]
Bonjour,

J'ai remarqué dernièrement que dans un groupe, seul 1 des widgets s'affichait

Exemple : 
**Config sur le WEB**
![Selection_014](https://user-images.githubusercontent.com/45817385/175901302-8d1237b5-1783-4b41-98cc-18b40fa3709e.png)

**Config sur le mobile**
![290063366_388364543358835_8427365022783249630_n](https://user-images.githubusercontent.com/45817385/175901394-ffdd586c-aaba-48e9-b3de-c9410f656a6a.jpg)

**Affichage sur le mobile**
![289997710_358536529759681_5984649047773085211_n](https://user-images.githubusercontent.com/45817385/175901425-cc05e2ef-de78-427f-8b87-9262568998b7.jpg)

N'hésitez pas à me dire s'il faut vous d'autres infos !

Loïc

**Comment by tomitomas** [comment]
Salut


Tu es en affichage standard ou avancée ?

(Clic long sur le nom du menu , editer)

**Comment by loicdelecroix** [comment]
Hello, en automatique : 
![289871715_439725034353982_6110909088364830742_n](https://user-images.githubusercontent.com/45817385/175905684-a40f712b-a1d0-481c-b771-de19557e1133.jpg)

**Comment by loicdelecroix** [comment]
Je viens de tester en forçant les 2 affichages, il semble qu'en mode Standard, ce soit OK, mais le mode Avancée reproduit le même soucis

**Comment by tomitomas** [comment]
perdu du coup ... dans l'app : `menu > pref > widgets et grilles`  ==> est ce que l'option `grille avancée` est activée ?

**Comment by loicdelecroix** [comment]
Oui, l'option dont tu me parles est bien activée

**Comment by loicdelecroix** [comment]
En effet, juste en bougeant un widget du groupe, la grille se met à jour, et les autres s'affichent bien !
Peut-être un redimensionnement auto à prévoir dans ces cas-là ? :)

Merci pour le coup de main (et la réactivité) en tout cas!
