### ISSUE TITLE
Configurez l'appareil : changement d'onglets, on perd les infos

### ISSUE THREAD

**Issue by olivvv59** [jared-94/JeedomConnect#20]
Bonjour,

J'étais entrain de configurer mes widgets.
J'en avais fait quelques un.

j'ai voulu basculer sur l'onglet pièce.
en revenant, j'avais perdu tous les widgets.

Je n'avais pas sauvegarder avant de passer à l'autre onglet.
Mais habituellement,
- soit on met un message d'avertissement
- soit c'est seulement en quittant la fenêtre qu'on perd des données

**Comment by jared-94** [comment]
Je n'arrive pas à reproduire ce bug...

Est-ce systématique ?

**Comment by olivvv59** [comment]
je vais retester pour trouver la marche à suivre.
j'ai juste prit l'application en main hier.

j'avais commencé à créer mes widgets. j'avoue que ça m'a découragé :-p

**Comment by olivvv59** [comment]
j'ai compris.
autant pour moi, j'ai crée plusieurs emplacemens des widgets

un emplacement Accueil/Volets/Lumière

Je me suis juste occupé des lumières

quand on quitte l'onglet .. on revient dans le premier menu dans la liste déroulante (Accueil).
Comme le mien est vide. Je pensais que j'avais perdu mes infos.

du coup, on ne perd pas les données mais on revient dans le haut de la liste déroulante.
Pour ça que j'étais dérouté

**Comment by jared-94** [comment]
OK tant mieux si t'as rien perdu !
Je ferme le sujet
