### ISSUE TITLE
Paramètres Réseaux Jeedom Connect en dehors du réseau local

### ISSUE THREAD

**Issue by stargateSGU** [jared-94/JeedomConnect#206]
Bonjour,
Après plusieurs tests avec mon smartphone Android, j'ai constaté, en connexion externe du réseau local, qu'en fait il faut killer l'application et la relancer pour que Jeedom Connect retrouve les paramètres réseaux externes. le switch entre les paramètres réseaux local et réseaux externes ne switch pas automatiquement.
Si cela peut aider à trouver une solution :) 
Sinon cette application est géniale et complète pour gérer sa domotique.
Encore bravo à Jared-94

**Comment by stargateSGU** [comment]
Bonjour,
Après plusieurs tests avec mon smartphone Android, j'ai constaté qu'en fait il faut killer l'application et la relancer pour que Jeedom Connect retrouve les paramètres réseaux. le switch entre les paramètres réseaux local et réseaux externes ne switch pas automatiquement.
Si cela peut aider à trouver une solution :) 
Sinon cette application est géniale et complète pour gérer sa domotique.
Encore bravo à Jared-94

**Comment by jared-94** [comment]
Salut !

Tu reproduis avec la dernière version ?

**Comment by stargateSGU** [comment]
Bonjour Jared-94,

Avec la version 1.4.0 je n'ai pas constaté le problème.

Merci pour cet excellent travail et support.

Bonne journée

Bernard
