### ISSUE TITLE
Mauvais port du Websocket quand bascule de réseau externe vers réseau interne

### ISSUE THREAD

**Issue by Andylias** [jared-94/JeedomConnect#209]
Bonjour,
J'ai configuré JeedomConnect avec le service WebSocket mais sur un port différent de 8090, le 59XX pour le réseau interne et le port 39XXX pour le réseau externe. La configuration réseau chez moi est ok.

Je redémarre le démon et scan le QR Code (que j'ai régénéré) avec mes téléphones pour me connecter à Jeedom via le réseau interne => Ok.
L'adresse et le port du Websocket interne sont bons dans l'interface du téléphone. Je bascule sur la 4G, l'adresse et le port du websocket sont là aussi bon, tout fonctionne sans encombre.

Si je rebascule sur le réseau interne (en ré-activant le wifi sur mon téléphone), l'adresse du WebSocket est bonne mais pas le port, qui prend le port par défaut : 8090. 

Je n'avais pas ce problème avant, ce n'est que depuis quelques semaines. Le problème est reproductible sur un autre téléphone. Au final, via le réseau externe cela fonctionne tout le temps mais sur le réseau interne, ça ne fonctionne qu'une seule fois après le scan du QR Code.

Jeedom Core : 4.2.20
Version JC : 1.3.1
DNS Jeedom : non

Equipements :
  TPH-Klem : v1.3.0 sur android [os : 31] (ws)
  TPH-Sab : v1.3.0 sur android [os : 30] (ws)

**Comment by Andylias** [comment]
> Salut,
> 
> (c'est plus pratique de passer par community :) )
> 
OK je le ferai pour les prochaines fois. Sry
J'ai testé via une appli hors JC et les paramètres des ports sont bons. Le QR Code donne donc les bonnes infos.

**Comment by tomitomas** [comment]
étonnant l'app est censé prendre et stocker les infos que tu viens de lire. 
du coup je laisserai @jared-94 regarder et répondre à son retour de congé, car faut vérifier le comportement interne à l'appli

**Comment by jared-94** [comment]
Le champs "port websocket" du plugin n'est pas utilisé par l'appli, seulement les adresses.
C'est donc les adresses qu'il faut vérifier.

Si nécessaire, ajouter :xxxx à la fin

**Comment by Andylias** [comment]
> Le champs "port websocket" du plugin n'est pas utilisé par l'appli, seulement les adresses. C'est donc les adresses qu'il faut vérifier.

C'est déjà le cas. Et elles sont bien transmises à l'appli via le QR Code. (ws://name.domain:port)

A mon sens, il y a un bug de l'app qui, dans le cas de l'utilisation d'un port qui n'est pas le port par défaut 8090, si on passe du réseau externe au réseau interne, l'app ne lit pas le port inscrit dans son fichier de config et prend le port par défaut.

**Comment by jared-94** [comment]
Non encore une fois aucun port par défaut ou autre n'est configuré dans l'app...

Si tu veux tu pourras me contacter en mp à mon retour de vacances et je regarderai

**Comment by jared-94** [comment]
Résolu
