### ISSUE TITLE
Freeze de l'application à la déconnexion

### ISSUE THREAD

**Issue by perarem** [jared-94/JeedomConnect#22]
Sur Android, l'application se gèle lors d'une déconnexion, (écran blanc) il faut la stopper manuellement pour la relancer.
Cela se produit aussi de façon très aléatoire lors du rechargement de la configuration.

**Comment by jared-94** [comment]
Oui je sais ça peut arriver parfois lors du rechargement de la config, si la config a changée.
En revanche qu'appelles-tu "déconnexion" ?

**Comment by perarem** [comment]
C'est l'utilisation de la commande "Se déconnecter" dans le menu "Préférences"

**Comment by jared-94** [comment]
Ah ok je vais vérifier ça merci !

**Comment by perarem** [comment]
A priori, plus de problème avec la version 0.17.1
