### ISSUE TITLE
Petit problème (ré)import widget

### ISSUE THREAD

**Issue by Gigatrappeur** [jared-94/JeedomConnect#222]
Bonjour,

Pour commencer, je suis tombé par hasard sur votre plugin jeedom, et j'avoue que je suis très impressionné par le travail que vous avez déjà réalisé.  
J'avais déjà fait des essais pour créer un plugin pour faire de l'envoie de notifications via le NotificationManager du navigateur mais avec un succès mitigé sur PC...

Pour en venir au fait, j'ai quelque soucis avec l'assistant pour créer certains widget, en particulier pour associer des icones.
Afin d'aller plus vite, j'ai exporté le JSON des widgets. Puis après modifcation et réimport, aucune modifications n'était visible.

Après investgation, il semble qu'il y ai 2 `json_decode`. Le second pose problème sans lever d'exception.

J'ai donc, simplement fait le test de commenter le `json_decode` de cette ligne, et ensuite, le code fonctionne.
https://github.com/jared-94/JeedomConnect/blob/1253a550493d2bae7cb356195aa21a688f8d9462/core/class/JeedomConnectWidget.class.php#L335

J'espère que vous pourrez rapidement corriger le problème

Cordialement,
Gigatrappeur

**Comment by tomitomas** [comment]
Salut,

Merci pour ton retour.

Pas de bug connu pour cette fonctionnalité qui existe depuis de nombreux mois.

Je t invite a nous rejoindre sur le forum pour que ca soit plus simple a suivre. 

A+

**Comment by Gigatrappeur** [comment]
Hello,

pas de soucis. J'ai pas encore pris le temps d'aller sur le forum.
Mais en tout cas, content que cela est pu aider.

Merci :-)
