### ISSUE TITLE
remplissage auto des actions ?

### ISSUE THREAD

**Issue by olivvv59** [jared-94/JeedomConnect#23]
J'ai été surpris (en bien) qu'il remplisse automatiquement l'état quand on choisit le "on" d'une lampe.

Par contre, il ne remplit pas le off. c'est dommage de ne pas être aller jusqu'au bout.

après je dis ça mais il y a peut être des contraintes que je ne connais pas.

**Comment by jared-94** [comment]
En effet, il y a dans certaines commandes action une commande info associée ce que je récupère.
Par contre les actions on et off par exemple ne sont pas reliée dans la config jeedom.

Après je pense utiliser les type générique pour faire ça mais ça me demandera un peu de travail !

**Comment by olivvv59** [comment]
je sais que c'est plus facile à dire qu'à faire.^^

il y a peut-être d'autres priorités ;-)

Je t'aurais bien aidé. Mais mes compétence en PHP date de la version 4.
Mais surtout, de mon coté, c'est une période compliquée pour gérer un développement.

**Comment by jolypas** [comment]
> En effet, il y a dans certaines commandes action une commande info associée ce que je récupère.
> Par contre les actions on et off par exemple ne sont pas reliée dans la config jeedom.
> 
> Après je pense utiliser les type générique pour faire ça mais ça me demandera un peu de travail !

Il y aussi du boulot pour que les plugin utilisent les bons génériques. C'est l'option prise par jeemate mais cela demande presque autant de boulot que d'affecter à la main dans les widgets à ce stade des dev.

**Comment by Mips2648** [comment]
La dernière beta permet la création de widget en mode quasi automatique en se basant sur les types génériques lorsque ceux-ci sont correctement renseignés pas les plugins (ou si l'utilisateur le fait manuellement)
Et comme ce n'est pas obligatoire on a le meilleur des deux mondes car on peut toujours créer les widgets manuellement ;-)
On peut donc fermer cette issue je pense
