### ISSUE TITLE
Pièce équivalent aux objets jeedom ?

### ISSUE THREAD

**Issue by olivvv59** [jared-94/JeedomConnect#24]
Bonjour,

j'ai vu qu'il y avait une notion de pièces dans Jeedom connect.

Par contre, je m'attendais qu'il y ait une corrélation entre pièces et la notion d'objets dans Jeedom.

c'est peut-être voulu pour que cela soit plus flexible. 
Mais c'est vrai que personnellement, j'ai recrée à la main mes objets Jeedom.

(désolé, pour toutes mes issues, c'est juste pour aider. j'essaye d'être constructif. Le produit est très sympa)

**Comment by jared-94** [comment]
Pas de soucis ;-)
C'est déjà dans le code il suffit juste d'attendre la prochaine mise à jour !

**Comment by olivvv59** [comment]
quelle réactivité !! super ^^
