### ISSUE TITLE
Problème d'icônes sur certains widgets

### ISSUE THREAD

**Issue by EraserHead67** [jared-94/JeedomConnect#25]
Salut et félicitations pour ton travail !

Je voulais te signaler un problème que je rencontre pour changer l'image principale de certains widgets, en particulier le widget "Mode".

J'ai pu en assigner une à un widget me permettant de choisir le mode "Jour" "Soir" "Nuit" correspondant à un virtuel.
Mais j'ai un autre widget "Mode" pour changer le mode d'un radiateur ; pour celui-là, impossible, j'ai toujours l'image par défaut, c.a.d le carré vert avec une flèche.
En revanche, pour les images assignées à chaque choix de mode, j'ai bien les images correspondantes.
Ci-joint une copie d'écran de ma config.

Je précise que le problème est dans l'affichage dans l'appli Android bien sûr ;-)

Si tu veux plus d'informations, n'hésite pas à me demander !

![Capture d’écran 2021-02-03 223715](https://user-images.githubusercontent.com/72168647/106812779-6746de00-6670-11eb-8080-89133748103c.png)

**Comment by jared-94** [comment]
Oui en effet merci !
Ce sera corrigé dans la prochaine mise à jour ;-)

**Comment by jared-94** [comment]
Normalement corrigé en 0.15.0
