### ISSUE TITLE
Groupe de lumière : Visibilité des Widgets plus explicite dans la liste déroulante

### ISSUE THREAD

**Issue by olivvv59** [jared-94/JeedomConnect#26]
Bonjour,

Je m'explique. 
Pour chaque pièce, j'ai crée un Widget Lumière (d'ailleurs, je vais surement y revenir dans une autre issue/évolution).

Quand je vais faire un groupe de Lumière pour éteindre plusieurs sources dans la même pièce.
j'ai une liste déroulante avec Lumière. (possibilité de mettre entre parenthèse l'intitulé de la pièce ? )

![image](https://user-images.githubusercontent.com/10774296/106973634-88ccc600-6753-11eb-8f04-208a6bc22ccd.png)

**Comment by olivvv59** [comment]
EDIT : d'ailleurs, je vois un bug en regardant ma capture.
Les lumières à la base, je les avais dans un menu Lumière en bas.

j'ai tout déplacé dans Le menu du bas : Accueil puis l'onglet Lumière (j'ai donc plus rien dans l'emplacement d'origine) .

**Comment by jared-94** [comment]
OK j'ai ajouté les pièces !
Pour le bug, oui l peut y avoir quelques widgets 'fantômes' s'ils ont été créés sur d'anciennes versions... ne pas en tenir compte ;-)

**Comment by jared-94** [comment]
Bug résolu normalement ;-)
