### ISSUE TITLE
possibilité de Cacher nom de widgets pour afficher la pièce ( par exemple) à la place ?

### ISSUE THREAD

**Issue by olivvv59** [jared-94/JeedomConnect#27]
bonjour,

j'ai tendance à faire des onglets par thèmes.
et pour certains widget ( comme la température), je met température comme nom de widget .
le seul truc qui varie : c'est la pièce ( et la valeur bien sûr)

du coup, comme on a une icône parlante sur le type, ça fait redondance.

je fais une capture. ça sera plus parlant ^^

![Screenshot_20210205-020908_Jeedom Connect](https://user-images.githubusercontent.com/10774296/106976078-0db9de80-6758-11eb-8e00-3466315bb6bc.jpg)

**Comment by jared-94** [comment]
Il suffirait de ne pas rendre obligatoire le nom ?

**Comment by olivvv59** [comment]
Après c'est peut-être juste une question d'affichage. 

ça permet quand même dans les menus déroulants de les identifier, non ?

**Comment by jared-94** [comment]
J'ai ajouté le nom de la pièce dans les menus déroulant.
Sinon a terme je pense qu'on pourra en effet personnaliser tous les champs texte

**Comment by tomitomas** [comment]
fixé dans la version beta 17
