### ISSUE TITLE
Images sous conditions

### ISSUE THREAD

**Issue by perarem** [jared-94/JeedomConnect#29]
Bonjour,

L'utilisation des nombres décimaux dans la fonction Images sous conditions de certain widget ne fonctionne pas, seuls les nombres entiers sont supportés. Est-ce normal ?

En pratique, un capteur de température renvoi un nombre décimal avec 1 voir 2 chiffres après la virgule suivant les capteurs. Du coup, on peut considérer qu'une température de 19°C correspond à une température réelle comprise entre 18,5°C et 19,5°C (la moyenne). Le problème est qu'actuellement on ne peut afficher une image qu'en fonction d'une température strictement supérieure (ou inférieure) à une valeur entière (19 donc) pour une température allant de 19,01°C à 20,00°C ce qui n'est pas très logique.

Il manque aussi les opérateurs >= et <=

**Comment by jared-94** [comment]
Bonjour,

en effet, j'ai converti en entier, je vais convertir en décimales maintenant !
Merci

**Comment by perarem** [comment]
Je confirme, c'est OK pour moi
