### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Damien3131** [jared-94/JeedomConnect#32]
Hello

I have Android 11 on Samsung Note 10 + and when I scan qrcode or I link manually app crashes.
I can speak French if needed and test.

Best regards

**Comment by jared-94** [comment]
Bonjour
Il me faudrait un peu plus de détails.
Est ce qu'il y a des widgets configurés ?
Si oui essai peut être de les désactiver un a un pour voir lequel pose problème
