### ISSUE TITLE
Suggestions sur Font-awesome/ Matérial Design

### ISSUE THREAD

**Issue by olivvv59** [jared-94/JeedomConnect#36]
Hello,

J'ai vu que tu avais permis la sélection des icônes grâce à une liste.
C'est beaucoup plus sympa que d'aller sur les sites respectifs pour aller chercher les codes des icones. 
J'y avais pensé mais je n'osais pas te le demander.

Par contre, quelques petites remarques  la dessus :

- Lorsqu'on clique pour voir les icones (Font awesome ou Material) :
il y a une petite latence (tu récupères sans doute les icones).
Juste une petite icones animée  .. ça permettrait de montrer que le site à bien reçu notre demande et qu'il rapatrie.
(le top, c'est de mettre une icone de chargement avec le fond assombri : le temps du chargement)
Cela pourrait éventuellement te servir pour d'autres choses qui demandent un peu de temps pour se mettre en place.

- Lorsqu'on sélectionne l'icone, il serait sympa d'afficher le code (la balise) généré avant de valider.
Cela permettrait de jouer un peu sur le CSS (couleur de l'icone, taille).
ça rendrait la chose la plus flexible 
(ou alors , si tu veux pousser le bouchon, tu peux créer graphiquement cette possibilité ... si tu ne veux pas que du code s'affiche).

- Enfin, perso, j'aime les designs minimalistes.
Cela serait bien de donner la possibilité de choisir ces icônes pour les widgets (tout en laissant le choix de la couleur/ taille : genre jaune quand la lampe est allumé/gris eteint)

Voila pour mes remarques.
A toi de voir ce que tu veux prendre ou pas :-)

en tout cas, elle est top ton application.
Beau travail 👍

**Comment by jared-94** [comment]
Oui merci des idées !
Le picker d'icônes n'est pas encore très au point en effet j'ai fait ça un peu vite fait.
Mon prochain chantier est justement de pouvoir choisir des icônes a la place des images dans les widgets !

**Comment by olivvv59** [comment]
les grands esprits se rencontrent 
^^

**Comment by jared-94** [comment]
J'espère pouvoir sortir une beta la semaine prochaine avec laquelle on pourra choisir des icônes avec option couleur ou images avec option noir et blanc

**Comment by olivvv59** [comment]
ça serait super 🙏

**Comment by jared-94** [comment]
Dispo dans la version 0.17.0 ;-)

**Comment by tomitomas** [comment]
fixé beta 17
