### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by loulou29** [jared-94/JeedomConnect#37]
En essayant d'ajouter un menu bas, je recois l'erreur:
`JeedomConnect&p=JeedomConnect&id=262#eqlogictab | 299 | Uncaught TypeError: Cannot read property 'split' of undefined
`

**Comment by jared-94** [comment]
Merci du retour
Avec quelle icône as tu ce bug ?

**Comment by loulou29** [comment]
En effet, j'ai pas mis d'icone
Je me suis ensuite rendu compte que c'etait obligatoire
Donc faut juste s'assurer qu'une icone a été choisie avant de proceder.

**Comment by jared-94** [comment]
Je vais améliorer ce point merci du retour !
