### ISSUE TITLE
Deux fois le même Widget dans une pièce 

### ISSUE THREAD

**Issue by jolypas** [jared-94/JeedomConnect#38]
Bonjour
Je me retrouve avec deux thermostats dans une pièce alors qu'il n'existe qu'un Widget 
![Screenshot_2021-02-20-10-56-29-499_com jeedomconnect app](https://user-images.githubusercontent.com/14258266/108591823-efb0c880-736a-11eb-9b35-57eb00a02854.jpg)

**Comment by jared-94** [comment]
Bonjour,
Je suis au courant je vais corriger prochainement !

**Comment by jolypas** [comment]
Corrigé en 0.16
