### ISSUE TITLE
Widget Multimédia

### ISSUE THREAD

**Issue by Ricardo544** [jared-94/JeedomConnect#43]
Hello Jared,

Tout d'abord merci pour ce magnifique travail, ton application et ton plugin pour Jeddom --> que du bonheur :o))

Juste une petite demande concernant un widget multimédia, comptes-tu en mettre un à disposition, un peu comme celui que l'on trouve dans le plugin SqueezBox Control : 
![Multimedia](https://user-images.githubusercontent.com/48009784/110029306-98303680-7d34-11eb-9e86-c4f6e38fe7f5.JPG)

Merci d'avance

@+

**Comment by jared-94** [comment]
Salut Ricardo !

Oui étant moi même grand fan de musique, j'ai clairement envie de faire ça !!
Par contre je peux pas trop te dire quand ça arrivera...

**Comment by Ricardo544** [comment]
Mes salutations du matin Jared,

Super bonne nouvelle alors en ces temps troubles :o))
C'est dans ta "todo list" c'est top !!

Bonne journée à toi.

**Comment by Ricardo544** [comment]
Salut Jared,

En fait tu l'as quasiment le Widget Multimédia, avec le widget WebView qui permet d'afficher une Url (Pochette de l'album) et les boutons (Play, Pause, Stop, Etc....) avec le Widget "générique action" un petit widget "Texte" pour afficher un texte (Nom de l'album, Artiste, durée restante, etc....).
Certes, c'est facile à dire mais pas forcement facile à mettre en place :o)) mais il comme dit plus haut, il ne manque pas grand chose.

Bonne soirée à toi.

Amicalement.

**Comment by jared-94** [comment]
Dispo sur la dernière beta !

**Comment by Ricardo544** [comment]
Salut jared,

Oui j'ai vu !!!!! merci à toi c'est parfait. 

Ton application pour Jeedom est tip-top

@+
