### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by olivvv59** [jared-94/JeedomConnect#47]
bonjour,

je te fais des suggestions à prendre ou pas ^^
- j'ai vu des personnes ne pas comprendre le fonctionnement de ton application. cela serait bien d'avoir un lien vers ta documentation accessible assez facilement ( a partir de l'application jeedom et/ou mobile).

- de temps en temps, quand notre plugin jeedom se met à jours. on se retrouve avec un message : nouvelle version de l'application ( un truc dans le genre).
cela serait bien de savoir quel numéro de version

- c'est un peu en rapport avec le point précédent.
tu devrais mettre une version sur le playstore ( en beta si tu préfères, pour le moment). ça faciliterait la mise à jour.
tu devrais d'ailleurs faire payer une petite somme ( pour te payer le droit d'utiliser le playstore) . au vue du travail, cela le vaut largement. et si tu veux garder le caractère gratuit, tu laisses la possibilité de télécharger manuellement comme aujourd'hui. 

- j'ai essayé les icônes font awesome et matérial design. ça commence vraiment à prendre forme. par contre, tu devrais utiliser de l ajax , notamment sur la recherche quand on tape. ça permet de ne pas bloquer l'application pendant que le logiciel fait sa recherche. 
si tu as besoin de plus d'information. je t'aiderais si tu veux.

bon boulot en tout cas 💪

**Comment by tomitomas** [comment]
salut @olivvv59 

1. comme tout plugin jeedom, un lien vers la documentation est disponible sur la page de configuration du plugin. Difficile de faire "plus simplel" puisque c'est le standard jeedom :) 

2. déjà demandé, déjà répondu : il va regarder aussi bien pour l'alerte côté plugin que côté apk.

3. déjà demandé 100 fois, déjà répondu 100 fois : c'est en cours. tu n'es peut etre pas au courant mais la publication d'un app sur le store ne se fait pas en un claquement de doigt ni en 30 sec, ca demande un certain nombre de validation. Le processus est donc en cours, et en attente de validation chez le google. 

4. la fonction de recherche est la même que celle de jeedom actuellement

**Comment by olivvv59** [comment]
> salut @olivvv59
> 
> 1. comme tout plugin jeedom, un lien vers la documentation est disponible sur la page de configuration du plugin. Difficile de faire "plus simplel" puisque c'est le standard jeedom :)
> 2. déjà demandé, déjà répondu : il va regarder aussi bien pour l'alerte côté plugin que côté apk.
> 3. déjà demandé 100 fois, déjà répondu 100 fois : c'est en cours. tu n'es peut etre pas au courant mais la publication d'un app sur le store ne se fait pas en un claquement de doigt ni en 30 sec, ca demande un certain nombre de validation. Le processus est donc en cours, et en attente de validation chez le google.
> 4. la fonction de recherche est la même que celle de jeedom actuellement

1) je t'invite à prendre en charge toutes les questions dans ce cas 😊

2) désolé, je ne suis pas tous les forums. c'est pour ça que je fais ça dans le github du projet . je t'invite aussi à faire tes demandes dessus. c'est un peu le but 😊

3) je ne suis pas au courant. cf question 2

4) si c'est dans jeedom, ça veut pas dire qu'on ne peut pas faire mieux 😊

je te remercie pour cette réponse qui n'apporte rien sauf d'être très désagréable. 😊

**Comment by jared-94** [comment]
Pour la 4. les PR sont les bienvenus !

Pour le Play Store il y a deux points qui font que ça prend du temps 
- la géoloc, il faut prouver que je ne récolte pas les données
- le fait qu'ils ne puissent pas tester l'appli (les employés de Google n'ont pas forcément un jeedom sous la main)

**Comment by olivvv59** [comment]
> Pour la 4. les PR sont les bienvenus !
> 
> Pour le Play Store il y a deux points qui font que ça prend du temps
> 
> * la géoloc, il faut prouver que je ne récolte pas les données
> * le fait qu'ils ne puissent pas tester l'appli (les employés de Google n'ont pas forcément un jeedom sous la main)

bonne idée !!
je regarderais cet après-midi si les douleurs me le permettent.

**Comment by olivvv59** [comment]
@jared-94 : j'ai fait une correction de mon coté pour améliorer les perfs. J'ai voulu faire une branche pour ne pas perturber votre travail. Mais je ne pense pas que j'ai les droits (ou je me débrouille mal ^^).

@tomitomas désolé pour cette échange, je comprends bien que vous devez avoir tout un tas de demande. Mais c'était juste des propositions sans pression. Je me suis peut etre mal exprimé. Mais j'ai ressenti de la tension dans ta réponse.

Pour la modif :
c'est pas grand chose 

plugins\JeedomConnect\desktop\modal\assistant.iconModal.JeedomConnect.php
`
$('#in_searchIconSelector').on('keyup',function() {
//debugger;
	var search = $(this).value()
  if (search.length < 2) { return; }
  ////////////// soucis de perf. avec show 
  /*$('.divIconSel').show()
	$('.iconCategory').show()*/
	$('.divIconSel').css({'display':'block'})
	$('.iconCategory').css({'display':'block'})
  $("#jeeCon").removeClass( "collapse" )
  $("#mdCon").removeClass( "collapse" )
  $("#faCon").removeClass( "collapse" )

	if (search != '') {
		search = normTextLower(search)
		$('.iconDesc').each(function() {
			if ($(this).text().indexOf(search) == -1) {
				//$(this).closest('.divIconSel').hide()
				$(this).closest('.divIconSel').css({'display':'none'})
			}
		})
	}

	var somethingFound = 0
	$('.iconCategory').each(function() {
		var hide = true
		if ($(this).find('.divIconSel:visible').length == 0) {
			$(this).hide()
		} else {
			somethingFound +=1
		}
	})
	if (somethingFound == 0) {
		//$('.generalCategory').show()
		$('.generalCategory').css({'display':'block'})
	}
})
`
j'aimerais vous aider beaucoup plus. c'est un super projet.
Mais beaucoup de mal à me concentrer en ce moment.

en tout cas, c'est un super travail tous les 2. Sur Facebook, 
beaucoup de personnes vous félicite et adore l'application.
(c'est d'ailleurs pour ça que j'ai parlé de la doc. ils demandaient des fonctionnalités existantes ou ne faisaient pas ce qu'ils fallaient. j'ai fini par leur mettre un lien vers la doc (qui est en plus très bien faite). Après , je ne les blame pas. j'avoue que quand j'ai commencé jeedom. je galerais à chaque fois pour trouver la doc

**Comment by tomitomas** [comment]
Salut @olivvv59 

C est surement le cote "court" de ma reponse qui fait penser a de la tension, mais il n'y en a pas. :) 
Il est vrai que de mon côté je trouve un peu penible de lire et repondre toujours la meme pcq les gens ne lisent pas (je parle de facon generale). Je suis actif sur le community, par contre je ne suis pas du tout le groupe sur FB, donc je comprends mieux ta remarque. 
(Attention pour les docs, je ne sais pas quel lien tu as donné, mais dorénavant les maj seront sur le repo JeedomConnectDoc !)


Pour les branches tu ne peux en effet pas en creer. Ce que tu peux faire faire c est un fork du projet sur ton espace a toi, puis realiser une "pull-request" pour envoyer tes modifs dans la branch de ce projet. La demande pourra alors etre traitée par l'un de nous pour appliquer le code. 

Pas plus mal que tu n'aies pas fait comme ca immédiatement. Il y a bcp de changements dans la prochaine version et le code bouge pas mal. 
On regardera pour intégrer tes modif. merci ! ;)

**Comment by olivvv59** [comment]
Hello @tomitomas 

tant mieux, s'il y a aucune tension.:-)

Je comprends mieux pour la branche. c'est pas moi qui me galèrait avec git .. ça va ^^

Pour la doc, j'ai donné ce lien la :
https://jared-94.github.io/JeedomConnect/fr_FR/?fbclid=IwAR2Z8qi0ErVvFp0KJycw20NAljduhtcoYWWgvHhUmvzUSzmPt9UUzb-Iyzk

Par contre, le code que j'ai mis. tu ferras gaffe. j'ai l'impression qu'il a viré des * ( donc il a décommenté les lignes show existantes dans la version d'origine) quand j'ai posté ici.

**Comment by tomitomas** [comment]
on sera plutot sur celui là dorénavant : 
https://jared-94.github.io/JeedomConnectDoc/fr_FR/

les principales modif dans ton code c'est principalement remplacer les .show ou .hide par des css !?

au final je vais laisser surement laisser @jared-94 regarder, car les modifs que tu donnes partent de master, alors que Jared a refait un certain nombre de chgt sur la dernier beta (par ex les 3 id suivant n'existent plus en beta : #jeeCon, #mdCon & #faCon).  de mon côté en beta, l'affichage et la recherche sont assez rapide je trouve. 

(par contre je suis pour le test `< 2` ! )

to be continued ...! :)

**Comment by tomitomas** [comment]
(ahhhh je comprends d'autant mieux les remarques, que Monsieur est admin du groupe sur fb :) :) :) :) )
la prochaine beta aura qlq changements avec des pré-requis, donc je me suis inscrit au groupe pour au moins donner cette info, histoire que les gens lisent ce qu'il y a à faire avant de betement appliquer la mise à jour!

**Comment by olivvv59** [comment]
> (ahhhh je comprends d'autant mieux les remarques, que Monsieur est admin du groupe sur fb :) :) :) :) )
> la prochaine beta aura qlq changements avec des pré-requis, donc je me suis inscrit au groupe pour au moins donner cette info, histoire que les gens lisent ce qu'il y a à faire avant de betement appliquer la mise à jour!

je ne suis pas admin.
ou alors, je ne suis pas au courant 😅

mais j'aide quand je peux.
et je propose des articles pour youdom avec l'accord des admins , juste pour partager mes bricolages si ça peut servir à quelqu'un.

**Comment by tomitomas** [comment]
par admin je voulais dire modérateur, mais ca n'a pas l'air d'etre ca non plus :)
j'ai vu qlq un de tes articles sur youdom et comme youdom est mod, j'ai (trop rapidement) fait un lien ! 

ya l'air d'avoir plusieurs posts en tt cas, en effet. 
a suivre ! ;)

**Comment by olivvv59** [comment]
> Merci je viens de tester en effet c'est plus rapide, sur une recherche, je suis passé de 2.3s à 0.7s !
> Par contre si on met le test <2 la recherche n'est plus réinitialisée (quand =0)
> J'avais déjà filtrer pour commencer la recherche au deuxième caractère

je t'avoue que j'étais tellement content d'avoir trouver un moyen plus rapide.
j'ai voulu créer une branche pour partager et faire ensuite une recette( je sais.. on push après normalement 😅). et j'ai zappé. sorry
je vais regarder ça. a moins que tu es parti pour.

**Comment by tomitomas** [comment]
c'est déjà intégré @olivvv59 

dans le commit 2209b3cf53973ea10b0340cb5a7cd6907da21157
et verra le jour avec la prochaine beta ;)

**Comment by tomitomas** [comment]
l'ensemble des points sont donc traités ! 
je cloture :)
