### ISSUE TITLE
Widget Thermostat

### ISSUE THREAD

**Issue by perarem** [jared-94/JeedomConnect#48]
Le slider consigne du widget thermostat n'est pas pratique, impossible de voir la température lors d'une action sur celui-ci, le doigt masque la valeur. Ne pourrait-on pas le remplacer par un slider à boutons +/- ou d'avoir le choix du type de slider ?

Bug : Lorsque l'on ajoute une température dans l'option "Nom", celle-ci est supprimée lors de la réédition du widget.
Je n'ai pas vérifier sur les autres options...

Bug : Les options "Modes", "Images ajoutées" et "Ajouter des infos" ne sont pas modifiables.

Suggestion : Sur Jeedom, nous avons la possibilité dans le plugin thermostat de définir une consigne de température pour chaque mode, dans mon cas je pointe un virtuel avec un slider à bouton +/- pour jouer sur la consigne de certain mode. Serait-il possible d'implémenter une telle fonction (sur le popup de changement de mode par ex.) ?

**Comment by jared-94** [comment]
Pour les boutons +/- je suis d'accord, c'est pas évident quand on veut une valeur précise, surtout quand on a des gros doigts ;-)

Pour l'info qui disparaît dans le titre, est ce qu'a la place tu as ton ID entouré de # ? Si oui ça a normalement été corrigé dans les dernières versions.

Pour les champs non modifiables c'est pas un bug c'est intentionnel. J'évite comme ça les erreurs dans les noms de commandes. Tu as juste à supprimer et rajouter.

Sinon je suis pas sur de bien comprendre pour le thermostat. Il me semble que as la consigne puis des 'modes' qui correspond à une valeur particulière de cette consigne. Le slider est le même non ?

**Comment by perarem** [comment]
Pour l'info qui disparait, oui c'est bien ça, nickel si c'est déjà corrigé ;-)

Pour les champs non modifiable, c'est dommage car en cas de duplication du widget cela aurait évité de resélectionner l'icone pour le mode et la condition + l'image pour l'image sous condition. Mais bon, si c'est voulu, je ferait avec.

Pour la consigne du widget, actuellement lorsque l'on joue sur la consigne on n'applique plus la consigne définie d'un mode. donné, c'est bien pour une action ponctuelle dans le temps. Moi je parle de pouvoir modifier la consigne programmée d'un mode.

**Comment by perarem** [comment]
Pour plus de clarté, je ferme cette issue pour en ouvrir une autre car la plupart des points ont été corrigés mais quelques bugs sont apparus dans la version 0.19.4 (et peut-être les précédentes...)
