### ISSUE TITLE
Fenêtre de sélection d'icone/image

### ISSUE THREAD

**Issue by perarem** [jared-94/JeedomConnect#49]
La fenêtre de sélection d'une icône est trop grande ou ne s'adapte pas à la résolution de l'écran. On est obligé de la redimensionner pour accéder au boutons de validation.

**Comment by jared-94** [comment]
merci je vais régler ça !

**Comment by tomitomas** [comment]
fixed by 2209b3cf53973ea10b0340cb5a7cd6907da21157

**Comment by perarem** [comment]
Validé.
