### ISSUE TITLE
Application Android non compatible

### ISSUE THREAD

**Issue by ktn001** [jared-94/JeedomConnect#50]
Bonjour,
J'ai installé le plugin via le market de Jeedom (version 2021-02-22 19:29:33) puis utilisé le lien indiqué dans la page de configuration (https://github.com/jared-94/JeedomConnect/releases/latest) pour obtenir le apk. Le lien m'a conduit vers la release 0.17.1.beta.

J'ai installé l'app sur mon Android, configuré le plugin, créer un appareil et généré le qrcode.

Enfin, j'ai pu scanné le QR code depuis l'app et j'ai eu le message "**Cette application requiert une version plus récente du plugin**"

Je vais certainement m'en sortir en installant le plugin depuis de github plutôt que depuis le market mais j'ai deux propositions d'ammélioration:

1. Faire en sorte que le bouton de qui se trouve dans la page de configuration même à la bonne version de l'app dans github
2. Ajouter un qrcode dans cette page qui donne l'url pour downloader l'apk (Il suffirait alors de simplement scaner ce code avec une app QR pour pouvoir simplement installer l'apk.

En tout les cas, merci beaucoup pour ce travail.

**Comment by tomitomas** [comment]
Salut @ktn001 

Faire l install depuis github ne resoudra pas ton probleme. 
La version du 2021-02-22 19:29:33 est la derniere stable (0.16.0), or tu as installé une apk 0.17.1.beta  donc beta. 
Donc forcement ca ne match pas ! 

Dans les prochaines maj, le msg d erreur sera plus explicite pour savoir quoi faire. 
En attendant je t invite a télécharger la bonne apk pour ta version de plugin : [apk 0.16 stable](https://github.com/jared-94/JeedomConnect/releases/download/0.16.0/JeedomConnect-0.16.0.apk)

**Comment by Padepanic** [comment]
Hi !
Il serait intéressant de voir au premier coup d'oeil quelle est la version installée du plugin (sur la page de configuration du plugin par exemple) et d'avoir un message "Installer l'application Androïd ayant le même indice de version que le plugin".

Actuellement j'ai la version 0.17.1 du plugin installée depuis Jeedom. J'ai pu le savoir en lisant le fichier "/var/www/html/plugins/JeedomConnect/plugin_info/ version.json". Pas simple !
De plus quand je clique sur le bouton [ Télécharger la dernière version de l'application pour Android ] c'est le fichier "JeedomConnect-0.18.0-beta.apk" qui est proposé au téléchargement... De quoi s'y perdre ! Heureusement on trouve le lien de l'APK qui va bien dans la documentation (chapitre 10). Cool !

Merci pour ton travail ;)

**Comment by tomitomas** [comment]
en fait il y a plusieurs options : 
1. lire la doc :) où il y a les liens entre version plugin et version apk (avec en plus les liens de téléchargement !)
2. depuis la beta 18.0, l'apk propose directement de télécharger l'application si elle n'est plus à jour 
3. pour les versions stable, l'appli est dispo depuis ce matin sur le store

il n'y a donc plus vraiment de sujet ! :)

**Comment by tomitomas** [comment]
4. (et également suivre ce qui se dit sur le forum peut aider ;) )

**Comment by Padepanic** [comment]
YES !!!
