### ISSUE TITLE
Geofence et batterie 

### ISSUE THREAD

**Issue by rhcpdu13** [jared-94/JeedomConnect#56]
Bonjour à tous ! 
J'utilise depuis quelques semaines l'application principalement pour le geofencing, qui fonctionne à merveille ! Elle fonctionne même trop bien... Elle fait fondre en neige ma batterie. 
Y aurait-il pas un moyen de réduire la fréquence du repérage ?
![Screenshot_20210319-092409_Device care](https://user-images.githubusercontent.com/15130377/111751511-e4cb5400-8894-11eb-93b1-72a4ce4bfd9c.jpg)

Merci par avance !

**Comment by jared-94** [comment]
Salut
Je vais voir oui pour personnaliser certains paramètres !

**Comment by rhcpdu13** [comment]
Ah par contre une petite question qui pourrait peut être expliquer le problème :
![Screenshot_20210319-142801_Jeedom Connect](https://user-images.githubusercontent.com/15130377/111787607-6f28ad80-88bf-11eb-8c07-e32c9726a9cc.jpg)
j'ai la case activer le tracking en permanence d'active. est ce obligatoire pour avoir le geofencing?

**Comment by jared-94** [comment]
Ah oui en effet tu peux la décocher. Le geofence continuera de fonctionner et ta batterie te diras merci ;-)
