### ISSUE TITLE
Plantage Thermostat

### ISSUE THREAD

**Issue by Khomotica** [jared-94/JeedomConnect#57]
Bonjour,

L'application plante systématiquement lorsque j'essaie d'accéder à un thermostat.

Version appli : 0.18.2
Version Android 10 

![Screenshot_20210321-234530](https://user-images.githubusercontent.com/59171393/111923555-1ebc7600-8aa0-11eb-94c5-e18977b02366.jpg)

Pouvez-vous regarder svp?

**Comment by tomitomas** [comment]
Ca va etre un peu compliqué de t aider sans plus de detail....
Comme par exemple une copie ecran de ta conf...

**Comment by Khomotica** [comment]
Un exemple du thermostat du salon ou ça plante :
![image](https://user-images.githubusercontent.com/59171393/111924378-8aa0dd80-8aa4-11eb-8316-cb448fe33b20.png)

Une partie du JSON envoyé :
`{
	"parentId": 3,
	"index": 0,
	"id": 24,
	"name": "#room#",
	"subtitle": "elapsedTime",
	"statusInfo": {
		"id": "1849",
		"type": "info",
		"subType": "string"
	},
	"setpointAction": {
		"id": "1864",
		"type": "action",
		"subType": "slider",
		"minValue": "0",
		"maxValue": "5"
	},
	"setpointInfo": {
		"id": "1847",
		"type": "info",
		"subType": "numeric",
		"minValue": "10",
		"maxValue": "40",
		"unit": "°C"
	},
	"tempInfo": {
		"id": "1854",
		"type": "info",
		"subType": "numeric",
		"unit": "°C"
	},
	"tempExtInfo": {
		"id": "1856",
		"type": "info",
		"subType": "numeric",
		"unit": "°C"
	},
	"modeInfo": {
		"id": "1862",
		"type": "info",
		"subType": "string"
	},
	"modes": [],
	"powerInfo": {
		"id": "1866",
		"type": "info",
		"subType": "numeric",
		"unit": "%"
	},
	"lockInfo": {
		"id": "1851",
		"type": "info",
		"subType": "binary"
	},
	"lockAction": {
		"id": "1852",
		"type": "action",
		"subType": "other"
	},
	"unlockAction": {
		"id": "1853",
		"type": "action",
		"subType": "other"
	},
	"statusImages": [],
	"type": "thermostat",
	"blockDetail": false,
	"enable": true,
	"room": 4
}`

J'ai essayé de minimiser les commandes mais rien n'y fait.

**Comment by tomitomas** [comment]
Pour commencer je pense que 'Consigne' et 'info consigne' ne sont pas bonnes

Dans 'consigne' met "salon | consigne" (qui est une action sur ton equipement)
Et dans "info consigne" il faut que tu mettes la.commande de ton equipement qui renvoie l information de quelle est la valeur de la consigne

**Comment by perarem** [comment]
C'est l'utilisation de Delta Consigne dans Consigne qui fait planter l'appli, j'ai eu le problème avec la version 0.17

**Comment by Khomotica** [comment]
Merci bcp @tomitomas et @perarem pour vos retours. En effet, cela marche bien si jet met la bonne info ('Thermostat' au lieu de 'Info Consigne').
Après et je ne sais pas si c'est lié, les images des thermostats (ici les radiateurs) n'apparaissent plus.
En modifiant la consigne directement sur mobile et remettant le mode qu'il faut, la elles réapparaissent.
Une fois sorti de l'appli, elles disparaissent :(

**Comment by jared-94** [comment]
Les image de thermostat sont normalement corrigées dans la 0.18.4.
Je ferme mais soit libre de ré ouvrir en cas de besoin

**Comment by Khomotica** [comment]
Perfect ça fonctionne maintenant merci.
Par contre un plantage de nouveau au démarrage ... J'ouvre un autre ticket
