### ISSUE TITLE
Plantage au démarrage 

### ISSUE THREAD

**Issue by Khomotica** [jared-94/JeedomConnect#59]
V. 0.18.4
Appareil : oneplus one 7 pro
Android : 11

J'ai supprimé tt les données de l'appli puis reconfig avec QR code ça marche la 1ere fois. Si je ferme et ré-ouvre après ça plante systématiquement

**Comment by tomitomas** [comment]
Avec la  version 19.3 les pages blanches devraient etre moins presentes  
Et les widgets qui posent probleme sont identifiés sur l application
