### ISSUE TITLE
Lettres du menu haut manquantes

### ISSUE THREAD

**Issue by giorgio83570** [jared-94/JeedomConnect#64]
Bonjour,
pas bien grave mais un peu...étrange !  sur mon menu haut il manque systématiquement la dernière lettre du nom. Par exemple 
Salon-Sejou  Etag  ...etc...
Et puis surtout bravo pour le taff et la réactivité 👍 
Gio

**Comment by tomitomas** [comment]
salut, 

le bug a déjà été remonté sur le forum. 
ça a l'air d'arriver sur certain téléphone uniquement (certaine personne se sont amusées à mettre des titres à rallonge juste pour montrer que tout aller bien chez eux :) )
il faut qu'on arrive à reproduire pour trouver une piste comme solution ... 
t'as quoi comme tel ?

**Comment by giorgio83570** [comment]
Merci de la réponse... et désolé je débarque un peu !!
J'ai un ONEPLUS 7TPRO sous Android10
NB : j'ai doublé la dernière lettre mais bon...  :-))

**Comment by tomitomas** [comment]
il me semble que ceux qui ont le soucis sont aussi sur OnePlus :)
à voir ...

**Comment by giorgio83570** [comment]
Maudit ou pas... ? :-)) Bon, si je peux aider pour les tests c'est volontiers !
Ceci dit, ça n'a rien à voir avec ce post, mais depuis la dernière bêta, je relance bien l'appli mais les commandes/états ne passent plus !  impossible d'allumer/éteindre une lumière :-(

**Comment by giorgio83570** [comment]
je ne sais pas si ça a un rapport mais l'ID d'un nouveau widget créé incrémente la valeur précédente même si tout a été effacé. Le compteur des ID n'est pas remis à 0 lorsqu'on supprime tout ou décrémenté qd on en supprime 1.

**Comment by jared-94** [comment]
Pas de lien a priori avec one plus car moi aussi j'en ai un et jamais pu reproduire ce bug...

Pour les commandes ce n'est pas normal... Quelle est ta config ?

**Comment by giorgio83570** [comment]
Bjr,
Je réponds depuis mon super oneplus 😊
Pour les commandes la mise a jour d'hier du plugin a corrigé le problème !
Pour la lettre manquante c'est très curieux mais je pense que ce n'est pas
la priorité pour vous...
Et encore bravo pour le super job !
cdt,
G.IEGER
Envoyé de mon smartphone

**Comment by tomitomas** [comment]
Plus de lettres manquantes avec la 19.4 normalement ! ;)
Je cloture
