### ISSUE TITLE
Lan Interne - Internet

### ISSUE THREAD

**Issue by Web-svg** [jared-94/JeedomConnect#65]
Hello,
Dans ma config du plugin, j'ai 2 adresses d'accès (URL + port) différentes.
Lorsque je quitte le réseau interne , je ne peux me connecter via l'url externe (seule l'adresse interne apparait dans la fenêtre d'authentification).
Si je saisis l'url externe, j'ai le message affiché en rouge sous le cadre de saisie 'Adresse Jeedom' -> Error : network error'.
PS: l'appli mobile Jeedom fonctionne (URL,certificat et port OK)
L'appli est installée sur android 10 xiaomi 9 pro

**Comment by jared-94** [comment]
La première étape fait seulement un ping sur Jeedom du coup c'est étrange ton souci...
Tu as bien mis l'URL complète sans /index... ?

**Comment by Web-svg** [comment]
Bonjour,
Alors oui c'est normal car je ne réponds pas au ping via Internet...
Pas de workaround possible ?
++


------ Message d'origine ------
De: "jared-94" ***@***.***>
À: "jared-94/JeedomConnect" ***@***.***>
Cc : "Web-svg" ***@***.***>; "Author" ***@***.***>
Envoyé : 03/04/2021 09:30:53
Objet : Re: [jared-94/JeedomConnect] Lan Interne - Internet (#65)

**Comment by jared-94** [comment]
En fait c'est pas un vrai ping c'est un appel à la méthode ping de l'API Jeedom (seule requête qui ne demande pas d'authentification)

Mais de toute façon une fois connecté même en interne l'URL externe est enregistrée par l'appli et utilisée si l'interne n'est pas dispo

**Comment by Web-svg** [comment]
C'est bien le soucis ...

![IMG_20210403_100153](https://user-images.githubusercontent.com/63095113/113472610-bb015800-9464-11eb-9a13-2dabb7a7a890.jpg)
![IMG_20210403_100137](https://user-images.githubusercontent.com/63095113/113472615-c2c0fc80-9464-11eb-93ad-e42fae79f1dc.jpg)

Connexion à Jeedom perdue, Tentative de reconnexion et ça boucle (Loop circle) .....

**Comment by jared-94** [comment]
Ton URL externe est sur port standard (80 ou 443) ?

**Comment by Web-svg** [comment]
Bonsoir,Désolé,  je n'avais pas vu ton mailSur le Lan interne c'est  en http port 80Sur Internet,c'est  en https sur 81/443 via un reverse proxy type haproxyPas de directives spéciales concernant le backend  utilisé car l'apps mobile jeedom tourne nickel ( design et qualité  mis à  part)Ps: je n'utilise pas  le web service sur le port 8090 et bien sûr, lui n'est pas accessible , ni 'naté'++
-------- Message d'origine --------De : jared-94 ***@***.***> Date : 03/04/2021  20:04  (GMT+01:00) À : jared-94/JeedomConnect ***@***.***> Cc : Web-svg ***@***.***>, Author ***@***.***> Objet : Re: [jared-94/JeedomConnect] Lan Interne - Internet (#65) 
Ton URL externe est sur port standard (80 ou 443) ?

**Comment by jared-94** [comment]
Sur ton premier screenshot on voit que tu es en 4g et que tu entres l'adresse interne c'est normal ?

**Comment by Web-svg** [comment]
Hello,
tout à fait mais à priori la config android s'en débrouille aussi bien 
avec l'apps jeedom originale que d'autres applications qui font du 
Webdav. Je ne me souviens plus ou exactement mais j'avais choisi de 
prioriser le wifi lorsque disponible pour éviter le flux 'data' sur 
3G/4G voire Edge.
PS: idem également sur un autre appareil configuré dans le plugin, mais 
même modèle et réglages.
++

------ Message d'origine ------
De: "jared-94" ***@***.***>
À: "jared-94/JeedomConnect" ***@***.***>
Cc : "Web-svg" ***@***.***>; "Author" ***@***.***>
Envoyé : 05/04/2021 13:49:23
Objet : Re: [jared-94/JeedomConnect] Lan Interne - Internet (#65)

**Comment by jared-94** [comment]
Le problème devrait être résolu dans la prochaine maj.
