### ISSUE TITLE
Géolocalisation de jeedomconnect et plugin Carburant

### ISSUE THREAD

**Issue by abcduweb** [jared-94/JeedomConnect#68]
Bonjour,
Je voulais vous féliciter pour le travail considérable que vous faite pour l'application.

Je voudrais savoir s'il est possible d'utiliser la géolocalisation du portable avec JeedomConnect pour le plugin Prix Carburant? 

Je vous remercie

**Comment by jared-94** [comment]
Bonjour, je ne sais pas je ne connais pas ce plugin.

Tout ce que je peux dire c'est que Jeedom Connect récupère en temps réel la localisation et la place dans une commande info sous la forme : latitude, longitude, altitude

Après on peut utiliser cette commande dans Jeedom

**Comment by abcduweb** [comment]
Bonsoir,
J'ai trouvé comment faire marcher les deux plugins en parallèle. Ça fonctionne vraiment bien.
Je vous remercie.

**Comment by tomitomas** [comment]
Et ... partager un peu plus de details sur le "comment" histoire que ca aide potentiellement d autres .... au lieu de simplement dire "j'ai reussi" ... non !?

**Comment by abcduweb** [comment]
C'est vrai je suis désolé pour ma réponse un peu courte ☹️.

J'ai utilisé le plugin "Localisation et trajet" de lunarok pour récupérer les valeurs geofencing du plugin JeedomConnect en créant un objet "portable".

Il faut ensuite configurer un objet "véhicule" dans le plugin "prix carburant" cocher la case "via localisation" et sélectionner l'objet "portable" précédemment créer.

Vous aurez ainsi le prix des carburants classé du moins chère au plus chère autour de votre portable.

Je pense faire un tuto détaillé sur ce point là sur mon site https://abcduweb.fr

En espérant ainsi vous aider.
