### ISSUE TITLE
Widget action ne marche plus 

### ISSUE THREAD

**Issue by Jonathan77390** [jared-94/JeedomConnect#69]
Bonjour, j'ai un problème depuis quelques jours sur l'app, après un bug sur mon jeedom, le plugin ne trouvais plus le chemin pour les image, j'ai donc désinstaller et réinstaller le plugin , j'ai refait tout mes widgets, mais plus aucun widget action ne fonctionnent, ceux infos fonctionne bien ( ouverture de fenêtre, température ), mais les action ( changement de mode , fermer tel volet , ouvrir la porte du garage, changer le thermostat ) tout ca ne fonctionne plus, j'ai une vibration du tel comme quoi il exécute la commande, mais rien ne se passe :/ 

Mail : jonathan.10@hotmail.fr
et je suis sur le groupe fb entraide jeedom : jonathan ballot

**Comment by tomitomas** [comment]
salut, 

il serait mieux de suivre le forum officiel plutot ;)

quelle version utilises tu ? 
comment te connectes-tu ? http ? ws ? via un dns jeedom ? si oui, as tu migré (sur leur derniere version de dns ? )

**Comment by Jonathan77390** [comment]
Alors : jeedom en 4.1.23 , jeedomconnect : 0.19.1 , version apk 0.19.2 retelecharger ya 1h , je me co via dns officiel, en flashant le qrcode , est ce que jai migrer le dns jen sait rien, c'etait senser se faire tout seul ^^
un log debug ??

**Comment by Jonathan77390** [comment]
[Log debug Jconnect.txt](https://github.com/jared-94/JeedomConnect/files/6312025/Log.debug.Jconnect.txt)

**Comment by Jonathan77390** [comment]
![20210414_175204](https://user-images.githubusercontent.com/82323233/114741177-cbf67700-9d4a-11eb-8148-2b370568c0e6.jpg)
![20210414_175232](https://user-images.githubusercontent.com/82323233/114741193-cf89fe00-9d4a-11eb-8296-ddb6ac8a9eed.jpg)

**Comment by tomitomas** [comment]
ca ne fonctionne pas, meme si tu es connecté en local depuis l'app ? 
(donc si tu es en wifi et en mettant ta connexion en 192.168.xxxx )

**Comment by Jonathan77390** [comment]
[Log debug Jconnect 2.txt](https://github.com/jared-94/JeedomConnect/files/6312142/Log.debug.Jconnect.2.txt)
Ligne pour mon volet salon, et dans mon virtuel c'est bien le meme id, et il marche sur le dashboard : ~~ result : [{"name":"Salon","upAction":{"id":"3280","type":"action","subType":"other"}

**Comment by Jonathan77390** [comment]
![Screenshot_20210414-180549_Jeedom Connect](https://user-images.githubusercontent.com/82323233/114742476-1298a100-9d4c-11eb-9366-19ef88001a76.jpg)
Connecter en direct ip , c'est pareil :/

**Comment by Jonathan77390** [comment]
Est ce que je doit attendre une future mise à jour, encore tout de s'installer, ou faire autre chose pour que ça remarche ??

**Comment by jared-94** [comment]
As tu testé sur la 0.19.4 ?

**Comment by Jonathan77390** [comment]
Ah super ca remarche avec la 0.19.4 ^^ 
Vous savez si une version iphone sera dispo prochainement ?

**Comment by tomitomas** [comment]
Top ! 

Pour ios, quand ca sera le cas, il y aura une comm dessus.
