### ISSUE TITLE
Widget Thermostat

### ISSUE THREAD

**Issue by perarem** [jared-94/JeedomConnect#73]
Version concernée : 0.19.4

Quelques bugs spécifiques du widget Thermostat.
Dans Jeedom :

> - Au moment de la ré-édition des options du widget, le champ "Nom" ne conserve que la première variable et supprime les autres (s'il y en a plusieurs) **ERRATA** voir ci-dessous

- Au moment de la ré-édition des options du widget, le champ "Nom" ne conserve que les variables #room# #statusText# et #lockText# toutes les autres variables sont supprimées.
- Lors de la modification du champ "Consigne", le champ "step" est vidé

Dans l'appli android V0.19.4 : **=> Corrigé en V0.19.5 Merci !**
- impossible de changer de mode, la sélection ne fonctionne pas (le bouton radio ne change pas d'état)
- Le titre dans le détail du widget renvoi le nom des variables plutôt que leur contenu
![photo_2021-04-18_00-16-24](https://user-images.githubusercontent.com/10147784/115128189-4558c880-9fdc-11eb-8c5f-e5552bb0468d.jpg)

**Comment by jared-94** [comment]
Merci pour le retour je vais voir pour corriger ça ;-)

Par contre pour les boutons de mode je n'ai pas de soucis... Il y en avait un sur la 0.19.3 mais normalement corrigé en 0.19.4.
Est ce que ça fonctionne en cliquant sur le texte ou l'image plutôt que le bouton radio ?

**Comment by perarem** [comment]
J'ai essayé les 2 cas, pas de réaction. 
Je suis bien en 0.19.4 sur l'appli android et Jeedom.
Du coup il faut cliquer en dehors de la fenêtre mode pour sortir mais ça tu dois déjà le savoir 
 ;-)

**Comment by jared-94** [comment]
Normalement corrigé en 0.19.5

**Comment by perarem** [comment]
Pour l'appli android, oui mais pas pour le plugin Jeedom.
Je suis bien en 0.19.5 
![Screen Shot 04-20-21 at 04 28 PM](https://user-images.githubusercontent.com/10147784/115413521-8841b880-a1f5-11eb-886f-d7d3a91c3547.PNG)

**Comment by perarem** [comment]
Evolution constaté avec la version 0.20.2 :
Plus de souci concernant le champ Nom. Les variables sont maintenant bien conservées.
Seul le problème du champ "step" vidé lors de la modification du champ "Consigne" subsiste encore.

**Comment by tomitomas** [comment]
Pour le titre (comme le sous titre), j ai en effet apporté le fix en 20.1.

Sur la partie step je ne suis pas certain qu il y en aura une par contre. Les chgt de commande fonctionne en "annule et remplace" , donc pas anormal que la valeur step soit vidée
Ca n est d ailleurs pas propre a la commande consigne du widget thermostat, mais c est comme ca pour toutes les options de chaque action de tous les widgets.
