### ISSUE TITLE
Résumé de pièce

### ISSUE THREAD

**Issue by Sergentgus** [jared-94/JeedomConnect#74]
Bonjour,

Déjà merci pour ce travail formidable !
J’espère que ma contribution sera utile.

Version 0.19.4
J'ai une différence entre le résumé de pièce global dans l'app et celle de Jeedom.
![image](https://user-images.githubusercontent.com/81466271/115150621-7fbc7700-a069-11eb-83ed-367f6a4d52e3.png)

![image](https://user-images.githubusercontent.com/81466271/115150645-9b278200-a069-11eb-9157-adc63ed1cf15.png)
Des val à zéro devrait être masquées mais apparaissent, et d'autre n'y sont pas du tout (Comme chauffage).

A votre disposition pour apporter des précisions.
Bon Courage,
Guillaume

**Comment by tomitomas** [comment]
> zéro devrait être masquées 
Il ne me semble pas que l on ait dit/ecrit ca !?

> d'autre n'y sont pas du tout
Si tu les as bien paramétrés il ny a en principe pas de raison qu ils ne s affichent pas. 
On peut voir l ecran ou ya l onglet résumé sur l assistant ?

**Comment by Sergentgus** [comment]
J'avais cru comprendre que le résumé global correspond au résumé dans Jeedom.
Dans mon cas, il est configuré comme ça : 
![image](https://user-images.githubusercontent.com/81466271/115220752-358ad280-a109-11eb-9dd3-966dd8777885.png)
Donc par exemple Alerte est masqué si nul, et je devrait voir lumières et Chauffage

**Comment by tomitomas** [comment]
Ma demande 

> On peut voir l ecran ou ya l onglet résumé sur l assistant ?

Je parle de la page sur l assistant JeedomConnect, onglet 'résumé'.
Pas la page de configuration de Jeedom

**Comment by Sergentgus** [comment]
Hargg... Désolé, j'avais effectivement raté cette page. Donc j'ai rien dit pour ce qui est de la liste des objets. En revanche, de pouvoir masquer les valeur à zéro comme suivant la config de Jeedom serait un plus.
Merci.
