### ISSUE TITLE
Plugin 0.19.5, app demande 0.20.0 

### ISSUE THREAD

**Issue by Jonathan77390** [jared-94/JeedomConnect#77]
Je pense qu'il doit y avoir un problème la , je viens de mettre à jour 0.19.5 sur jeedom et téléphone,  et l'appli du tel me demande la 0.20.0 ^^ 
![Screenshot_20210421-023801_Jeedom Connect.jpg](https://user-images.githubusercontent.com/82323233/115480469-d0d79100-a24a-11eb-94f4-bb9fdd35a3a8.jpg)

**Comment by jared-94** [comment]
Bonjour
La version 0.20.0 est dispo sur le play store

**Comment by Jonathan77390** [comment]
Ah oui ba merde je suis passer par github pour télécharger lapk et play store me disait aucune mise à jour 🤔🤔

**Comment by tomitomas** [comment]
C est surtout que tu as installé le plugin stable, mais l apk beta ... du coup ca match pas...!

**Comment by Jonathan77390** [comment]
Non j'ai le plugin bêta également ^^

**Comment by Jonathan77390** [comment]
C'est bon ça remarche , j'ai desinstaller et réinstaller en passant par le play store et c'est bon ^^

**Comment by tomitomas** [comment]
oui oui on vient de comprendre ce qui s'est passé cette nuit, sans vraie action de notre part ! ^^

**Comment by Jonathan77390** [comment]
D'accord ^^ pas de soucis, je me doutait bien que yavais eu un oublie quelques part ^^ rien de méchant ^^
