### ISSUE TITLE
[BUG] Authentification impossible

### ISSUE THREAD

**Issue by pedipaco** [jared-94/JeedomConnect#78]
Bonjour,

Après saisie user/MDP un popup apparaît : "choisir un équipement", sans action possible :
![Screenshot_20210426_174658_com jeedomconnect app_edit_87577288751740](https://user-images.githubusercontent.com/55596935/116205611-37bee380-a73e-11eb-81ec-ef95f861114c.jpg)

Voici le contenu de la log après avoir cliquer sur "Se connecter" :
```
[2021-04-27 09:46:16][DEBUG] : HTTP API received {"method":"GET_PLUGIN_CONFIG","params":{"userHash":"<myUserHash>","apiKey":null},"jsonrpc":"2.0","id":1619509677455}
[2021-04-27 09:46:16][DEBUG] : HTTP API received {"method":"GET_AVAILABLE_EQUIPEMENT","jsonrpc":"2.0","id":1619509677514,"params":{"apiKey":null}}
```

Plugin configuré (adresses http interne et externes)
Testé depuis Huawei P30
Application à jour : 0.20.0
Version jeedom : 4.1.22

**Comment by tomitomas** [comment]
et ... est ce que tu as créé des équipements sur le plugin ..!?

**Comment by pedipaco** [comment]
Je n'arrive pas à en ajouter :
![Screenshot_20210427_105709_com android chrome_edit_128753686311603](https://user-images.githubusercontent.com/55596935/116215829-53c78280-a748-11eb-9907-4ceda22df5a1.jpg)

**Comment by tomitomas** [comment]
Du coup le "bug" n est pas sur l appli... puisque tu n as pas créé d equipement, c est plutot normal que tu ne puisses pas en selectionner un !!??... 


"Erreur 500" ne nous apprend pas grand chose. 
Le message apparait a quel moment ? Apres avoir cliqué sur quel bouton ?
Qu est ce qu il y a dans les logs JeedomConnect ? Et dans http.error ?

**Comment by pedipaco** [comment]
L'erreur 500 apparaît lorsque j'essaie d'ajouter une équipement, lorsque je clique sur "Ajouter un appareil" puis "ok".

Voici le contenu de la log jeedomConnect :
`[2021-04-27 11:12:18][DEBUG] : Generate qrcode with data {"useWs":0,"httpUrl":"<myURL>","internalHttpUrl":"<myURL>","wsAddress":"","internalWsAddress":"","apiKey":"<APIKey>","userHash":"<userHash>","eqName":"Test"}`

Contenu de la log http.error :
```
[Tue Apr 27 11:19:42.066946 2021] [php7:error] [pid 3892] [client 192.168.1.24] PHP Fatal error:  Uncaught Error: Call to undefined function ImageCreate() in /var/www/html/plugins/JeedomConnect/core/php/phpqrcode.php:985
Stack trace:
#0 /var/www/html/plugins/JeedomConnect/core/php/phpqrcode.php(943): QRimage::image(Array, 3, 4)
#1 /var/www/html/plugins/JeedomConnect/core/php/phpqrcode.php(3302): QRimage::png(Array, '/var/www/html/p...', 3, 4, false)
#2 /var/www/html/plugins/JeedomConnect/core/php/phpqrcode.php(3094): QRencode->encodePNG('{"useWs":0,"htt...', '/var/www/html/p...', false)
#3 /var/www/html/plugins/JeedomConnect/core/class/JeedomConnect.class.php(544): QRcode::png('{"useWs":0,"htt...', '/var/www/html/p...')
#4 /var/www/html/plugins/JeedomConnect/core/class/JeedomConnect.class.php(688): JeedomConnect->generateQRCode()
#5 /var/www/html/core/class/DB.class.php(168): JeedomConnect->preInsert()
#6 /var/www/html/core/class/eqLogic.class.php(966): DB::save(Object(JeedomConnect), false)
#7 /var/www/html/core/ajax/eqLogic.ajax.php(463): eqLogic->save()
#8 {main}
thrown in /var/www/html/plugins/JeedomConnect/core/php/phpqrcode.php on line 985, referer: http://myurl/index.php?v=d&m=JeedomConnect&p=JeedomConnect
```

**Comment by tomitomas** [comment]
ton jeedom tourne sur quel type de machine ?

**Comment by pedipaco** [comment]
Raspberry pi 3b+

Pour information, la génération de qrcode fonctionne avec l'application app mobile de jeedom.

**Comment by tomitomas** [comment]
oui, sauf qu'on n'utilise pas forcément les meme librairies !...

tu peux donner les infos 'Version PHP' et 'Version OS' disponible sur la page santé de jeedom stp ?

**Comment by pedipaco** [comment]
![Screenshot_20210427_114031](https://user-images.githubusercontent.com/55596935/116220921-68f2e000-a74d-11eb-821f-b95d250bbbc6.jpg)

**Comment by tomitomas** [comment]
visiblement il manque une librairie sur ta machine ... 
je vais creuser voir ... 

est ce que tu as le plugin JeeXplorer sur ton jeedom ?

**Comment by pedipaco** [comment]
Merci pour ton aide
Je viens d'installer ce plugin si besoin

**Comment by tomitomas** [comment]
en attendant de trouver une solution, il faudrait que tu ailles modifier un fichier
ouvre le plugin jeeXplorer, sur la gauche navigue dans les répertoires pour aller : `plugins\JeedomConnect\core\class\JeedomConnect.class.php`

normalement à la ligne 544 tu devrais avoir 
```
QRcode::png( json_encode($connectData), self::$_qr_dir . $this->getConfiguration('apiKey') . '.png');
```

change cette ligne en : 
```
try{
	QRcode::png( json_encode($connectData), self::$_qr_dir . $this->getConfiguration('apiKey') . '.png');
}
catch (Exception $e) {
	log::add('JeedomConnect', 'error', 'Unable to generate a QR code : ' . $e->getMessage());
}
```

puis clique sur le bouton `Enregistrer et ferme`

retourne sur la page du plugin JeedomConnect et essaie d'ajouter un équipement. 
il y aura un message d'erreur et le QRCode ne sera pas généré, mais l'équipement devrait se créer et te permettre d'utiliser l'application en saisissant les infos de connexions à la main, comme tu l'as déjà fait.

**Comment by pedipaco** [comment]
En effet cela fonctionne mais sans le qrcode.

Je viens d'installer le paquet php7.3-gd sur ma raspberry, après un restart du service http l'ajout d'équipement fonctionne et la génération du qrcode aussi.

Merci pour ton aide

**Comment by tomitomas** [comment]
c'est en effet ce paquet `php7.3-gd ` qui manque, mais étonnant que tu sois le seul à nous avoir remonté le soucis. 
et je ne voulais pas te faire taper des commandes en ssh ne connaissant pas ton niveau d'aisance avec unix ;)
