### ISSUE TITLE
Crash scroll menu haut

### ISSUE THREAD

**Issue by pdeliot** [jared-94/JeedomConnect#79]
Avec la version 0.20.0, quand je scroll vers la droite pur changer d'onglet (ou que je click sur un onglet (menu du haut) l'application crash (Ecran blanc, puis rechargement)

Si je garde un doit appuyé pour laisser le scrolling "en cours", j'ai accès à tous les ongletz et widget.
Dés que je lâche ça crash.

J'ai essayé de réinitialiser la config: même problème.

Testé sur une autre téléphone: même problème.

![Screenshot_20210427-111618_Jeedom Connect](https://user-images.githubusercontent.com/10339047/116219404-de5db100-a74b-11eb-9f40-67911d3302fd.jpg)
![Screenshot_20210427-112559_Jeedom Connect](https://user-images.githubusercontent.com/10339047/116219418-e1f13800-a74b-11eb-814d-c5bcfae57991.jpg)
On relache.. : crash...

**Comment by tomitomas** [comment]
déjà abordé et solutionné sur le forum : 

https://community.jeedom.com/t/suite-mise-a-jour-reboot-de-lapplication-avec-le-menu-haut/59450/19
