### ISSUE TITLE
Suggestion: Groupe de notification

### ISSUE THREAD

**Issue by Yannickbru** [jared-94/JeedomConnect#80]
Tout d'abord,
un grand merci et félicitation pour cette application.
Je recherche comment envoyer une notification à tous les appareils liés au plugin en même temps donc si ce n'est pas implémenté ça pourrait être une bonne idée.

Bonne continuation et bon courage.

Yannick

**Comment by jared-94** [comment]
Salut,
C'est dispo dans la nouvelle version beta !
