### ISSUE TITLE
Suggestion : Modifier Icone de base d'un Widget ou ...

### ISSUE THREAD

**Issue by Web-svg** [jared-94/JeedomConnect#81]
Hello,
J'utilise sans soucis le widget 'Fenêtre' pour obtenir le status (ouvert/fermé) d'une électrovanne.
Dans le gestionnaire du plugin, le look & feel est une fenêtre.
Serait-il ou est-il possible de pouvoir modifier l'icone ?

**Comment by tomitomas** [comment]
Hello 

et non. 
la customisation des icones est possible pour l'appli (en fonction ou pas du statut), mais pas de chgt dispo pour la visualisation sur la pag principale du plugin.

**Comment by Web-svg** [comment]
OK merci de la réponse, c'est effectivement ce que je fais et côté appli, c'est bien mes images qui prennent place.

**Comment by tomitomas** [comment]
A la limite, plutot que de prendre un widget lumiere tu peux prendre un widget `generique switch`, histoire d avoir un icon plus neutre sur la page principale ;)

**Comment by Web-svg** [comment]
Yep!
