### ISSUE TITLE
Suggestion : Widget Web View

### ISSUE THREAD

**Issue by Web-svg** [jared-94/JeedomConnect#82]
Hello,
Dans le widget Web View, serait-il possible d'avoir un champ distinct pour insérer l'URL selon que l'on est en mode local ou remote ? ...et qui serait pris en compte selon le mode de connexion effectif (CQFD)
++

**Comment by Web-svg** [comment]
Hello,
Des news ? 
++

**Comment by jared-94** [comment]
Salut, ça sera dans la prochaine version ;-)

**Comment by tomitomas** [comment]
dispo Version beta 0.21.3 (22/07/2021)

**Comment by Web-svg** [comment]
Vu ...mais pourquoi dans le widget webview plutôt que Caméra (forcément 
plus complet vs les options). Un choix ou une raison particulière ?
++

------ Message d'origine ------
De: "ToMtOm" ***@***.***>
À: "jared-94/JeedomConnect" ***@***.***>
Cc : "Web-svg" ***@***.***>; "Author" ***@***.***>
Envoyé : 03/08/2021 11:42:10
Objet : Re: [jared-94/JeedomConnect] Suggestion : Widget Web View (#82)

**Comment by tomitomas** [comment]
Pardon mais ... c est quoi la question !?

**Comment by Web-svg** [comment]
Sorry ...les vacances, la fatigue ...

------ Message d'origine ------
De: "ToMtOm" ***@***.***>
À: "jared-94/JeedomConnect" ***@***.***>
Cc : "Web-svg" ***@***.***>; "Author" ***@***.***>
Envoyé : 04/08/2021 08:18:10
Objet : Re: [jared-94/JeedomConnect] Suggestion : Widget Web View (#82)
