### ISSUE TITLE
Canal de notification

### ISSUE THREAD

**Issue by DavidWinckel** [jared-94/JeedomConnect#88]
Bonjour,
Il semble y avoir un (petit) bug avec les canaux de notifications supplémentaires 

Version: 
- App: 0.20.0
- Jeedom 4.1.22
- Plugin version: 2021-04-20 14:58:55

Reproduction: 
- Configurer un appareil avec un canal de notification spécial. Voici ma configuration : 
![image](https://user-images.githubusercontent.com/57551491/117159382-83b5fc00-adc0-11eb-9956-12a7920cb86f.png)
- Installer l'application de zéro et scanner le QR code de conf
- Faire un test de notification du canal supplémentaire
- Les notifications de ce canal ne fonctionne pas (note: android n'affiche pas le canal supplémentaire dans les paramètres de notification système)

Pour forcer l'ajout du canal, il suffit simplement de faire une sauvegarde de la configuration des notifications côté jeedom et le canal est ajouté et fonctionne immédiatement. 

Merci d'avance

Bonne journée. 

PS: bon sang c'est formidable votre application ! Un immense merci / bravo !

**Comment by jared-94** [comment]
Bonjour, oui en effet il faut d'abord connecter l'appareil et ensuite configurer les notifications.
C'est le bouton sauvegarder qui envoie les données sur les canaux à l'appli
