### ISSUE TITLE
Application crash au lancement après période en "veille"

### ISSUE THREAD

**Issue by DavidWinckel** [jared-94/JeedomConnect#89]
Bonjour,
J'ai un comportement étrange avec l'application. Après une longue période en "veille" ; dès que je la relance elle crash (la fenêtre commence à s'ouvrir et se ferme directement) sans message d'erreur. Si je relance elle fonctionne immédiatement. 

App: 0.20.0
Jeedom 4.1.22
Plugin version: 2021-04-20 14:58:55

Y a t-il des logs que je peux aller consulter pour comprendre de quoi il retourne ?

Merci d'avance.

**Comment by DavidWinckel** [comment]
Un détail intéressant. Il semble que je ne reçoive pas toujours les notifications. 
Pour le moment à chaque fois qu'une notification n'est pas arrivée; si je lance l'application dans la foulée elle est justement dans l'état dont je parle ci-dessus. Crash au lancement. 
Peut-être que c'est justement une notification qui vient mettre la zone? 
A noter que ma femme à exactement le même téléphone, même configuration et widget mais pas l'ensemble des notifications (une partie seulement). Et chez elle c'est OK. 
J'ai aussi remarqué que chez elle le téléphone est vu comme "accroché" dans le plugin alors que moi non.
![image](https://user-images.githubusercontent.com/57551491/117293679-fe8b1f80-ae71-11eb-8352-6b1e54a1e8c0.png)
![image](https://user-images.githubusercontent.com/57551491/117293752-1793d080-ae72-11eb-9b64-5595763e6a65.png)
Même après déconnexion / reconnexion. 

Je vais essayer de me mettre à iso notification par rapport à elle pour voir...

**Comment by DavidWinckel** [comment]
J'ai fini par trouver le rapport de bug. Je l'ai envoyé via Android.
![image](https://user-images.githubusercontent.com/57551491/117397779-28d5ef00-aefd-11eb-8a42-30cb2779124f.png)

https://github.com/software-mansion/react-native-screens/issues/17

A noter que je peux avoir le comportement sur demande maintenant. Dans les options pour développeurs il suffit de cocher "Ne pas conserver les activités" et l'application crash à chaque lancement au lieu d'une fois de temps en temps.

**Comment by jared-94** [comment]
Hello!

Très intéressant ça merci beaucoup !
Je vais appliquer le fix on verra ce que ça donne ;-)

**Comment by DavidWinckel** [comment]
Bonjour Jared, 

Merci pour le fix.

Vous pouvez le simuler sur votre téléphone en cochant la case "Ne pas conserver les activités". J'arrive à le reproduire sur un autre téléphone. Par contre l'autre téléphone ne va jamais le faire "en temps normal"... Je dois avoir une configuration particulière. Je vous tiens au courant si je tombe dessus.

Bonne journée.

**Comment by DavidWinckel** [comment]
Bonjour, 
Le fix semble OK. Du moins plus de problème depuis la dernière beta. 
Merci !
