### ISSUE TITLE
Suppression widget impossible

### ISSUE THREAD

**Issue by ghicat** [jared-94/JeedomConnect#90]
Bonjour,
Après avoir inclus un widget fils dans un autre, puis supprimé le fils, il m'est impossible d'accéder à la configuration du widget père. J'ai le message **m=JeedomConnect&p=JeedomConnect&id=JeedomConnect line 2 > scriptElement** lorsque je clique sur le widget.

**Comment by tomitomas** [comment]
Salut, 

la marche à suivre :
https://community.jeedom.com/t/help-supprimer-un-widget-qui-pose-pb/60160

**Comment by ghicat** [comment]
Top tomitomas

Merci
