### ISSUE TITLE
Suggestion : Mode Kiosque / Kiosk

### ISSUE THREAD

**Issue by Web-svg** [jared-94/JeedomConnect#98]
Hello,
C'est peut-être hors sujet mais un mode kiosk permettrait d'utiliser Jeedom connect directement via la navigation existante mais sans 'tout' ce qui est autour, au moins en visu directe, de façon à pouvoir l'utiliser en mode commande, un peu comme le permettait l'interface d'Imperihome...

++

**Comment by jared-94** [comment]
Salut !
Je suis pas sur de bien comprendre ton message mais depuis la beta 0.20.4 l'appli peut être définie comme launcher Android.

**Comment by Web-svg** [comment]
Hello,
honte à moi, je n'avais pas lu! nickel!
++
